### PR TITLE
Fixes part of #437

### PR DESCRIPTION
**Pull request by jimmyshah**
Adds frameon=true from #437 , I closed the previous PR

### CODE REVIEW

**Comment by jimmyshah** [comment]
I think I'm having some trouble understanding the problem with my submission. Would it be possible to receive some feedback?

**Comment by rebeccabilbro** [comment]
Hey there @jimmyshah and thanks for checking out Yellowbrick and for helping us work through our (ever growing 😅) backlog of issues! 

Here's what's happening with your PR; you've globally modified the `manual_legend` utility, which is used by many of our visualizers. As a result, your change has broken many of those existing visualizers (for instance, `ParallelCoordinates`, [which already passes in a frameon argument](https://github.com/DistrictDataLabs/yellowbrick/blob/develop/yellowbrick/features/pcoords.py#L517)). 

The request in #437 is to do something similar with `Manifold` as is currently done in `ParallelCoordinates` (e.g. passing the `frameon` kwarg [into the call to `manual_legend`](https://github.com/DistrictDataLabs/yellowbrick/blob/develop/yellowbrick/features/manifold.py#L403), which already knows how to consume any `**legend_kwargs` that get passed in), not to modify the `manual_legend` utility function directly. 

Note that when you make this change, it should fix all the CI errors, but we may need to work through some new broken image tests for `Manifold` &mdash; if you want to get a jump on figuring those out, you can read up on our visual image tests [here](https://www.scikit-yb.org/en/develop/contributing/developing_visualizers.html#testing) and [here](https://github.com/DistrictDataLabs/yellowbrick/blob/develop/tests/README.md#image-comparison-tests)!

Apologies for the confusion, and hope this is helpful!

**Comment by jimmyshah** [comment]
Thank you so much for the elaborate response @rebeccabilbro !  It was really helpful and I understand the issue more clearly now. I'm going to try working on this again in a bit.

**Comment by jimmyshah** [comment]
@rebeccabilbro Thank you again for your all of your help! It looks like my commit is passing the Travis CI check according to the site, but it is still showing it as being queued here. Is there something else that I need to do?

**Comment by jimmyshah** [comment]
@rebeccabilbro This is so wonderful to hear! Thank you so much, and I look forward to future contributions. I can use the feature branch convention going forward as well, my apologies about that.

**Pull request merged**
