### PR TITLE
[WIP] Adding Support for Probability Calibration Curve

### PR DESCRIPTION
**Pull request by saurabhdaalia**
Trying to Implement fixes for #365 

https://nbviewer.jupyter.org/github/saurabhdaalia/ProbablityCurve/blob/master/Curve.ipynb
I have put together this very naive sort of example to get an idea that what are we trying to implement exactly. Would love to get some feedback over it to put down some initial steps to implement the feature.

P.S: Also, are there any IRC/Communication channels to discuss and communicate

### CODE REVIEW

**Comment by lwgray** [comment]
@saurabhdaalia Thanks for following up on the comment in #365.  When we get back from our 2 week hiatus we will review this.  Currently all communication is done via github or our list-serve https://groups.google.com/forum/#!forum/yellowbrick

**Comment by saurabhdaalia** [comment]
Sure, Thank you

**Comment by rebeccabilbro** [comment]
Hey there @saurabhdaalia &mdash; your notebook looks like a good start! If you'd still like to move forward with working on this PR, the next step is to push some code that we can review so that we can see how you've implemented `ProbabilityCalibrationCurve` under the Yellowbrick API

**Comment by saurabhdaalia** [comment]
@rebeccabilbro , yes I am planning to move forward to start implementing the visualiser, currently drafting my GSOC Proposal which will incorporate this feature. As soon as I done drafting the proposal, I will start pushing code to it. 
Thank you

**Comment by rebeccabilbro** [comment]
Thanks @saurabhdaalia &mdash; since Google has its own forum for submitting applications and our PRs are focused solely on reviewing code contributions to Yellowbrick, I’m going to go ahead and close this PR. Please feel free to reopen later if you decide to pursue work on the probability calibration curves!

**Pull request closed without merging**
