### PR TITLE
Correct detail docs in KneeLocator

### PR DESCRIPTION
**Pull request by Haebuk**
i think it's more appropriate to write in docs the k scores , not silhouette scores.

### CHECKLIST

- [x] _Is the commit message formatted correctly?_
- [ ] _Have you noted the new functionality/bugfix in the release notes of the next release?_

- [ ] _Included a sample plot to visually illustrate your changes?_
- [x] _Do all of your functions and methods have docstrings?_
- [ ] _Have you added/updated unit tests where appropriate?_
- [ ] _Have you updated the baseline images if necessary?_
- [ ] _Have you run the unit tests using `pytest`?_
- [x] _Is your code style correct (are you using PEP8, pyflakes)?_
- [x] _Have you documented your new feature/functionality in the docs?_

- [ ] _Have you built the docs using `make html`?_

### CODE REVIEW

**Comment by lwgray** [comment]
@rebeccabilbro What are your thoughts on this?

**Comment by lwgray** [comment]
@arvkevi What are your thoughts on this doc change?

**Comment by arvkevi** [comment]
This change indicates that the the `y` values are not always silhouette scores, which is true. In fact, the default type of k score from the `KElbowVisualizer`, the only place where `KneeLocator` is used, is distortion. But changing this line to "k scores" doesn't convey a lot of information the user. Looking past the fact that the documentation wasn't accurate, when it was "silhouette scores" I knew exactly what those y values represented. Conversely, "k scores" leaves me somewhat confused.  @Haebuk & @lwgray I think the change away from "silhouette scores" is good, my only suggestion would be to include some additional context. What do you think about adding an additional sentence, something along the lines of: "The type of k scores are determined by the metric parameter from the KElbowVisualizer class."

**Comment by lwgray** [comment]
@arvkevi I think your suggestion works.  @Haebuk If you think it is cool, Can you append your changes with @arvkevi suggestion

**Comment by Haebuk** [comment]
@arvkevi I recognized It's inaccurate expression not only `silhouette score` but also `k scores`. I appended a line you suggest. thank you.

**Comment by Haebuk** [comment]
sorry, I'm not familiar with signing to a commit, so I wonder why just one commit verified..

**Comment by lwgray** [comment]
@Haebuk Can you post the output of git log --show-signature

**Comment by Haebuk** [comment]
I tried again but it was same..
```
commit a59db60710914f50b399dadc15af53939e38ff40 (HEAD)
gpg: Signature made 2022년 04월  1일 금 오전 10:39:00
gpg:                using RSA key 3543047715BA2919CA7049686E00C369040FABF7
gpg: Good signature from "jaesungRyu (rsa4096) <cwryu6252@naver.com>" [ultimate]
Author: Jaesung Ryu <cwryu6252@naver.com>
Date:   Tue Mar 29 07:38:26 2022 +0900

    append more details about k scores

commit 436aea9dc39e279ebd1e0bce004e54821acf98c4
gpg: Signature made 2022년 04월  1일 금 오전 10:38:17
gpg:                using RSA key 3543047715BA2919CA7049686E00C369040FABF7
gpg: Good signature from "jaesungRyu (rsa4096) <cwryu6252@naver.com>" [ultimate]
Author: Jaesung Ryu <cwryu6252@naver.com>
Date:   Tue Mar 29 07:38:26 2022 +0900

    append more details about k scores

commit 2f6aba88810fa37200abac04ddecbc24f32b1c3d
Author: Haebuk <cwryu6252@naver.com>
Date:   Fri Mar 25 16:16:54 2022 +0900

    Correct detail in KneeLocator
```

I tried `git rebase --exec 'git commit --amend --no-edit -n -S' -i 2f6aba` but did not updated.

**Comment by Haebuk** [comment]
```
commit 2f6aba88810fa37200abac04ddecbc24f32b1c3d
Author: Haebuk <cwryu6252@naver.com>
Date:   Fri Mar 25 16:16:54 2022 +0900

    Correct detail in KneeLocator

commit 6fb2e9b7e5b2998c6faa4dcca81a4b0f91bf29b4
gpg: Signature made 2022년 02월 27일 일 오전  7:02:41
gpg:                using RSA key 4AEE18F83AFDEB23
gpg: Can't check signature: No public key
Author: Larry Gray <lwgray@gmail.com>
Date:   Sat Feb 26 15:02:41 2022 -0700

    Remove try/except clauses from tests (#1224)

    This PR fixes issue #1218 which reported technical debt in which there were several try/except clauses within tests that needed to be removed. This was first identified by @rebeccabilbro in PR #1197

commit 62423f4e57eab21f704cef08ae9a11deab45b9cc
gpg: Signature made 2022년 02월 26일 토 오전 11:20:49
gpg:                using RSA key 4AEE18F83AFDEB23
gpg: Can't check signature: No public key
Author: Larry Gray <lwgray@gmail.com>
Date:   Fri Feb 25 19:20:49 2022 -0700
```

**Comment by lwgray** [comment]
try, command below
git rebase --exec 'git commit --amend --no-edit -n -S' -i 6fb2e9b7

**Comment by Haebuk** [comment]
@lwgray yeah.. I think it works but also create too many duplicated commits..(I think it's my fault.)

**Comment by lwgray** [comment]
@Haebuk Sorry about the hassle... It appears that your original commits were not signed either.  You will have to sign them also.

**Pull request closed without merging**
