### PR TITLE
[MRG] Add FeatureCorrelation to Documentation

### PR DESCRIPTION
**Pull request by zjpoh**
#553

### CODE REVIEW

**Comment by rebeccabilbro** [comment]
Hi @zjpoh! Just checking in to see how this is going - it looks like you're getting ready to add a new page to the docs to document how to use the new `FeatureCorrelation` visualizer - thank you!! I'm excited for this visualizer to be documented and discoverable to our users! 

This is based on the checklist I use, in case you find it helpful!

 - [ ] create a new file, feature_correlation.rst, inside `docs/api/target` that says a little bit about the use case for the visualizer, and shows an example plot. Make sure it has this at the bottom:
    ```
    API Reference
    -------------
    .. automodule:: yellowbrick.target.feature_correlation
        :members: FeatureCorrelation
        :undoc-members:
        :show-inheritance:
    ```
 - [ ] create a new file, feature_correlation.py, inside `docs/api/target` that generates the images for the documentation, and stores them in `docs/api/target/images`
 - [ ] add a line to the file gallery.rst that links to the example plot:
    ```
    Target Visualizers
    ------------------
    
    .. image:: api/target/images/feature_correlation.png
        :width: 200px
        :height: 100px
        :alt: Feature Correlation
        :target: api/target/feature_correlation.html    
    ```

**Comment by zjpoh** [comment]
Ready for review.

**Comment by rebeccabilbro** [comment]
Thank you @zjpoh! @Kautumn06 is currently building your docs locally and reviewing; she'll get back to you soon with any suggestions!

**Comment by Kautumn06** [comment]
This looking really great @zjpoh! I'll review it this afternoon and get back to you with any comments or suggestions.

**Comment by Kautumn06** [comment]
Hi @zjpoh – the tests passed so the changes have now all been merged in. Thank you again for all of your hard work on the `FeatureCorrelation` visualizer and for creating the documentation!

**Pull request merged**
