### PR TITLE
Fixes to support scikit-learn 0.24

### PR DESCRIPTION
**Pull request by bbengfort**
I have made the corrections proposed by @bbengfort : https://github.com/phbillet/yellowbrick
After launching the tests, I have this result:
30 failed, 951 passed, 213 skipped, 21 xfailed, 40 xpassed, 24 warnings in 709.65s (0:11:49)

### CODE REVIEW

**Comment by bbengfort** [comment]
@phbillet would you mind updating the PR message with your comments?

**Comment by phbillet** [comment]
I made some corrections in tests folder and suppressed my comments:
24 failed, 1147 passed, 22 skipped, 21 xfailed, 40 xpassed, 24 warnings in 761.46s (0:12:41)

There is a problem with python 3.6 in Travis CI, unfortunately I do not know how to fix it, some help could be useful.

**Comment by bbengfort** [comment]
Hi, @phbillet thanks again for working on this issue and looking into it. Unfortunately, it appears that we've run out of our build credits on Travis-CI and the tests are no longer running. We've never encountered this issue before, so we're not sure how to resolve it - I'm looking into how we can increase our open-source credits. I'm sorry to say that we might have to delay looking into the scikit-learn 0.24 stuff until it's resolved and the earliest I can get to it is Saturday. I hope you understand! 

Screen Shot 2021-02-03 at 15 23 07

**Comment by bbengfort** [comment]
Hi @phbillet -- I actually got a chance to work on this tonight. Thank you so much for your efforts, your investigation into these issues helped solve a lot of problems with the scikit-learn 0.24 compatibility - particularly your find of the `shuffle=True` keyword. Because of the CI issue and because of some other tricky details with scikit-learn get and set params and inspect, I was forced to make the changes in a different PR - #1147. I'm going to close this PR in favor of that one, but we'll make sure that you're efforts are recognized in our changelog: 

https://github.com/DistrictDataLabs/yellowbrick/pull/1147/files#diff-b7f8a8784d5eff6e6b1b2c2529b831cd86132c49699fe48e0d23c17ad4e2d7deR11

Let me know if you'd like your full name there or just your GitHub handle. 

We'll also include you in the commit message so you get recognition as having participated in that PR. 

Thank you again for your help and contributions!

**Comment by bbengfort** [comment]
@phbillet Thank you again so much for your help! We merged #1147 and made sure you had co-author attribution:

Screen Shot 2021-02-09 at 08 19 58


Glad to have you as a Yellowbrick contributor!

**Pull request closed without merging**
