### PR TITLE
Fix sklearn.utils usage to correspond to scikit-learn's public/private API

### PR DESCRIPTION
**Pull request by Paulj1989**
Importing KElbowVisualizer from yellowbrick.cluster produces ```ImportError: cannot import name 'safe_indexing' from 'sklearn.utils'``` (#1137).

I have made the following changes:

1. Added _try except_ statement that attempts to import ```safe_indexing``` and then ```_safe_indexing``` if this produces an ImportError.

### Sample Code

```python
try:
    # See #1137: this allows compatibility for scikit-learn >= 0.24
    from sklearn.utils import safe_indexing
except ImportError:
    from sklearn.utils import _safe_indexing
```

### TODOs and questions

Still to do:

- [ ] Fix failing tests

Questions for the @DistrictDataLabs/team-oz-maintainers:

- [ ] This is my first PR contributing to a package, and I tried to follow the documentation for contributing, but I'm not sure if I'm missing anything in terms of my plan/process?
- [ ] Does this change need documentation?
- [ ] Should tests be run on all of the repository? Or should they be more targeted? 

### CHECKLIST

- [ ] _Is the commit message formatted correctly?_
- [ ] _Have you noted the new functionality/bugfix in the release notes of the next release?_

- [ ] _Included a sample plot to visually illustrate your changes?_
- [ ] _Do all of your functions and methods have docstrings?_
- [ ] _Have you added/updated unit tests where appropriate?_
- [ ] _Have you updated the baseline images if necessary?_
- [ ] _Have you run the unit tests using `pytest`?_
- [ ] _Is your code style correct (are you using PEP8, pyflakes)?_
- [ ] _Have you documented your new feature/functionality in the docs?_

- [ ] _Have you built the docs using `make html`?_

### CODE REVIEW

**Comment by rebeccabilbro** [comment]
Hello again @Paulj1989 and thank you for taking a crack at this! It's always such a good feeling when a user is so willing to jump in and become a contributor! 

I took a preliminary look at the test failures, and it appears there are some more substantial API changes as of scikit-learn 0.24 that are causing issues with our `ClassificationScoreVisualizers` (and possibly other things). 

I attempted to work through them locally by upgrading to 0.24 on my machine, but unfortunately, there appears to be [something wrong with 0.24 that prevents it from building correctly on macOS 10.13](https://github.com/scikit-learn/scikit-learn/issues/19063), which is what I currently have access to. We may need to wait until they push a patch that makes the new version of scikit-learn installable on my computer, or else until another YB maintainer with a different OS is able to take a look. 

I will keep following the thread over on the sklearn issues about the macOS installation problems and hopefully there will be a resolution soon!

**Comment by bbengfort** [comment]
@rebeccabilbro @Paulj1989 Perhaps we should make a quick change to [requirements.txt#L4](https://github.com/DistrictDataLabs/yellowbrick/blob/develop/requirements.txt#L4) to:

```
scikit-learn>=0.20,<0.24
```

Then create an issue to manage the other breaking API changes while keeping an eye on the macOS build issue? That would potentially allow us to merge this PR and close #1137 so we could get other fixes together in time for a 1.3 release. 

Meanwhile, I'm on OS X 11.1 -- so I'll attempt to build scikit-learn 0.24 to see if I can assist here, but I wouldn't be surprised if the build issue also existed for me.

**Comment by rebeccabilbro** [comment]
Hello again @Paulj1989; I went ahead and merged the test requirements change (that @bbengfort mentioned above) in a separate PR (#1136), so we can go ahead and move forward with your PR now! I've also pulled from `develop` into your branch to get rid of the CI errors we were seeing before, so be sure to pull from your remote branch so that you'll have the latest version locally on your machine.

It looks like all that's left for you to do is a bit of import statement aliasing (e.g. `from sklearn.utils import _safe_indexing as safe_indexing`). That will make sure we don't get that Flake8 error in CI (since the those tests are now running against `scikit-learn>=0.20,<0.24`), and also that the import will work without us having to change anything else in the `_split_fit_score_trial` method. That should clear up the rest of the issues so that we can merge your PR in. 

Let me know if you have any other questions, and thank you again for not only identifying the new sklearn API issues but also jumping in to help with Yellowbrick!

**Comment by Paulj1989** [comment]
That's great. Thanks for the work @rebeccabilbro and @bbengfort. I'm hoping to get to this in the next couple days!

**Comment by rebeccabilbro** [comment]
Sounds good @Paulj1989!

**Review by bbengfort — APPROVED** [review]
Hi @Paulj1989 there is kind of a tangle of things going on with Ttravis-CI, scipy 1.6, scikit-learn 0.24 and Python 3.7 … so we're going to go ahead and merge this in to see if we can untangle it. Thank you so much for submitting this PR and thanks for being a Yellowbrick contributor! 

@DistrictDataLabs/team-oz-maintainers -- note that I'm merging breaking changes into `develop` - but I'll do my best to fix them ASAP!

**Pull request merged**
