### PR TITLE
Additional tests for elbow detection in Elbow Visualizer

### PR DESCRIPTION
**Pull request by pswaldia**
This PR adds tests for a recently merged PR #813. 

I have added the following tests:   
1.  Added `tests/test_utils/test_kneed.py` that contains tests for `KneeLocator` class implemented in `kneed.py` 
2. Tests related to  `DataGenerator` have been removed since we do not require it in yellowbrick implementation of `kneedle` method

@bbengfort I ran the tests for this particular file and all tests passed. Please have a look .
Thanks.

### CODE REVIEW

**Comment by ndanielsen** [comment]
@pswaldia Thank you so much for this PR. My sincere apologies for the delay in review this. The maintainers team was at pycon and we are still playing catch up. 

These units tests are great and well detailed. Good job on these. :1st_place_medal: There is one type of test missing which is an image comparison test. Here is the documentation for [writing one](https://www.scikit-yb.org/en/develop/contributing/developing_visualizers.html#image-comparison-tests).

I suggest one `image comparison` test modeled after this current test with the main difference being that `locate_elbow=True`:
https://github.com/DistrictDataLabs/yellowbrick/blob/8978b433a2df2a3012f36650e0aec532a6671479/tests/test_cluster/test_elbow.py#L262-L284

I'm happy to accept this PR and you can open another one with an `image comparison` test, or you are welcome to add it to this PR. Please let me know soon.

Thanks again for all the work that you've done on contributing this additional functionality (with tests!!!) to yellowbrick. :100:

**Comment by ndanielsen** [comment]
@pswaldia lastly, please not that I merged `develop` into this PR. So you'll need to update your local branch.

**Comment by pswaldia** [comment]
@ndanielsen I will update this PR soon with the image comparison test.

Thanks.

**Comment by ndanielsen** [comment]
@pswaldia just a quick check on this. I can add the image comparison test in if needed so we can close this one out.

**Comment by pswaldia** [comment]
@ndanielsen apologies for the delay. It would be very helpful if you can add that test. I have been a little busy over past few days to have a look at this pending pull request. 
Thanks.

**Comment by ndanielsen** [comment]
@pswaldia thanks for letting me know. I'll merge this in and add that test.

Thanks for your efforts on this.

**Pull request merged**
