### PR TITLE
Update kneed algorithm

### LINKED ISSUE #1120: Update kneed
The [kneed](https://github.com/arvkevi/kneed) library has been updated a couple of times (with bugfixes!) since it was incorporated into the yellowbrick code. I would like to update the knee finding algorithm to be consistent with the [0.7.0 release](https://github.com/arvkevi/kneed/releases/tag/v0.7.0) of kneed.

Would you welcome a PR to update the code? Thanks!

### PR DESCRIPTION
**Pull request by arvkevi**
This PR closes #1120 by updating the kneedle, knee/elbow detection algorithm in `kneed.py`.

### CHECKLIST

- [ ] _Is the commit message formatted correctly?_
- [ ] _Have you noted the new functionality/bugfix in the release notes of the next release?_

- [ ] _Included a sample plot to visually illustrate your changes?_
- [x] _Do all of your functions and methods have docstrings?_
- [x] _Have you added/updated unit tests where appropriate?_
- [x] _Have you updated the baseline images if necessary?_
- [x] _Have you run the unit tests using `pytest`?_
- [x] _Is your code style correct (are you using PEP8, pyflakes)?_
- [x] _Have you documented your new feature/functionality in the docs?_

### CODE REVIEW

**Comment by arvkevi** [comment]
Only some of the new functionality in kneed has been ported in this PR to limit the number of lines added. I excluded the polynomial fit functionality and argument validation.

**Comment by arvkevi** [comment]
I'll keep hacking, I didn't see the unit tests in `test_cluster/test_elbow.py`.

**Review by bbengfort — APPROVED** [review]
@arvkevi this looks great, thank you so much for taking the time to update our port of your library. I also appreciate that you carefully selected what features and changes to add to minimize the number of additions. You're right that we don't necessarily need polynomial fit for our use case, and in terms of argument validation -- hopefully since this is internally used we won't get into issues with the parameters. It was very kind of you to enhance the test coverage to 100% as well; I think this will make it simpler for us to maintain the port in the future.

You're a good friend to Yellowbrick and we really value our partnership. Please don't hesitate to ask if there is any way we can return the favor!

**Comment by arvkevi** [comment]
Thanks for reviewing @bbengfort. It's great to contribute to a tool that has provided so much utility in my day-to-day work 😄.  Don't hesitate to ping me if there are ever problems or general questions. However I did, finally, create [proper documentation for kneed](http://kneed.readthedocs.io/). Also, after a few years of wondering if the algorithm was implemented correctly, I found *some* comfort when the original author [cited the repo on their homepage](https://faculty.insead.edu/ville-satopaa/research).

**Pull request merged**
