### PR TITLE
Add train alpha and test alpha to residuals.py and alpha param to pca.py

### PR DESCRIPTION
**Pull request by naresh-bachwani**
The following changes were made to Residuals referenced in #590 and #589 : 

1. Added new parameters train_alpha and test_alpha to specify the opacity of train and test data respectively in `residuals.py`

2. Added new parameter alpha to `pca.py` to specify the opacity.

### CODE REVIEW

**Comment by lwgray** [comment]
@naresh-bachwani Thank you for this PR.  We are currently on a 2-3 week hiatus and will take a look at it when we return.  Again thanks

**Comment by lwgray** [comment]
@naresh-bachwani Again thanks for the PR.  It would be a great help if you could split this into 2 PRs, one for residuals and the other for PCA.  I will commence to reviewing them as soon as this is done.

**Comment by naresh-bachwani** [comment]
Hello @lwgray,
In the later commits, I have made changes related to both PCA and residuals in the same commit. I would like to know what needs to be done in order to deal with this. Should I close the current PR? If not please give me broad guidelines regarding how to deal with this problem. I would be grateful if you could help me.

**Comment by lwgray** [comment]
i suggest you open two new PRs and apply the appropriate changes from this PR to the new ones.  you can later close this PR

**Comment by naresh-bachwani** [comment]
@lwgray, thanks for help.

**Comment by naresh-bachwani** [comment]
Thank you for your help @lwgray. I am closing this PR as you advised.

**Pull request closed without merging**
