### PR TITLE
Added AppVeyor configuration

### PR DESCRIPTION
**Pull request by bbengfort**
AppVeyor is a CI tool for Windows builds. Added CI for Python 2.7 and 3.6 on Windows as well as Miniconda 4.4.10.

### CODE REVIEW

**Comment by bbengfort** [comment]
Looks like this is going to be a tad tougher than I thought, but still possible. Right now the image comparison tests are failing because they cannot locate the `baseline_images` path:

```
self = <tests.test_features.test_pcoords.ParallelCoordinatesTests testMethod=test_normalized_pcoords>
extension = '.png'
    def _actual_img_path(self, extension='.png'):
        """Determines the correct outpath for drawing a matplotlib image that
            corresponds to the unittest module path.
            """
        module_path, test_func_name = self._setup_imagetest()
>       module_path = os.path.join(*module_path)
E       TypeError: join() takes at least 1 argument (0 given)
tests\base.py:79: TypeError
________________ ParallelCoordinatesTests.test_parallel_coords ________________
```

**Comment by bbengfort** [comment]
And updates: I wrapped all of the image comparison logic for `assert_images_similar` into a single class, `ImageComparison`. The `ImageComparison` object is callable and saves the state of a single
assertion statement (removing it from `VisualTestCase` so we can refactor to using all `pytest` instead of `unittest`). During this encapsulation I also added a lot of `os.path` handling to ensure that tests worked (hopefully) on Windows as well as on Posix, continuing the integration with AppVeyor.

`ImageComparison` now also raises an assertion error when nothing has been drawn on the axes object supplied (even if a title or axis labels have been added). This is further safety for some of our tests that just had empty images in them.

Updated the `ImageComparisonFailure` exception to use our own internal exception instead of Matplotlib's and made the exceptions a lot more readable.

Part of the refactor included a `test_meta.py`, which actually tests the `ImageComparison` class and some of our other testing utilities like the `RandomVisualizer`.

Updated `ROCAUC` to raise an exception on no curves instead of drawing an empty image. Updated `test_scatter.py` to use the correct `ImageComparisonFailure` exception class.

**Comment by NealHumphrey** [comment]
@bbengfort I tried running the tests on Windows. I don't really understand this error - though it could be related to my virtual environment, which I had some weird problems with when trying to run the code. 

This is with Windows 10, Anaconda install of Python 3, with a conda environment that has all the modules in `tests/requirements.txt` conda-installed (or pip installed in the case of pyflake-* that failed on conda). 

```
(yb) C:\Users\humph\Documents\Github\yellowbrick\tests>python -m pytest .
Traceback (most recent call last):
  File "C:\Users\humph\Anaconda3\envs\yb\lib\site-packages\_pytest\config.py", line 443, in import_plugin
    __import__(importspec)
  File "C:\Users\humph\Anaconda3\envs\yb\lib\site-packages\_pytest\capture.py", line 12, in <module>
    from tempfile import TemporaryFile
  File "C:\Users\humph\Anaconda3\envs\yb\lib\tempfile.py", line 45, in <module>
    from random import Random as _Random
  File "C:\Users\humph\Documents\Github\yellowbrick\tests\random.py", line 17, in <module>
    import numpy as np
  File "C:\Users\humph\Anaconda3\envs\yb\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import add_newdocs
  File "C:\Users\humph\Anaconda3\envs\yb\lib\site-packages\numpy\add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "C:\Users\humph\Anaconda3\envs\yb\lib\site-packages\numpy\lib\__init__.py", line 8, in <module>
    from .type_check import *
  File "C:\Users\humph\Anaconda3\envs\yb\lib\site-packages\numpy\lib\type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "C:\Users\humph\Anaconda3\envs\yb\lib\site-packages\numpy\core\__init__.py", line 74, in <module>
    from numpy.testing.nosetester import _numpy_tester
  File "C:\Users\humph\Anaconda3\envs\yb\lib\site-packages\numpy\testing\__init__.py", line 12, in <module>
    from . import decorators as dec
  File "C:\Users\humph\Anaconda3\envs\yb\lib\site-packages\numpy\testing\decorators.py", line 20, in <module>
    from .utils import SkipTest, assert_warns
  File "C:\Users\humph\Anaconda3\envs\yb\lib\site-packages\numpy\testing\utils.py", line 15, in <module>
    from tempfile import mkdtemp, mkstemp
ImportError: cannot import name 'mkdtemp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\humph\Anaconda3\envs\yb\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\humph\Anaconda3\envs\yb\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\humph\Anaconda3\envs\yb\lib\site-packages\pytest.py", line 72, in <module>
    import pytest
  File "C:\Users\humph\Anaconda3\envs\yb\lib\site-packages\pytest.py", line 77, in <module>
    _preloadplugins()  # to populate pytest.* namespace so help(pytest) works
  File "C:\Users\humph\Anaconda3\envs\yb\lib\site-packages\_pytest\config.py", line 118, in _preloadplugins
    _preinit.append(get_config())
  File "C:\Users\humph\Anaconda3\envs\yb\lib\site-packages\_pytest\config.py", line 128, in get_config
    pluginmanager.import_plugin(spec)
  File "C:\Users\humph\Anaconda3\envs\yb\lib\site-packages\_pytest\config.py", line 450, in import_plugin
    raise new_exc
ImportError: Error importing plugin "capture": cannot import name 'mkdtemp'
```

**Comment by bbengfort** [comment]
@NealHumphrey thanks for taking a look. A similar error was reported [scikit-learn[(https://github.com/scikit-learn/scikit-learn/issues/4620) when running tests on Windows with Anaconda. I found the following on [SO](https://stackoverflow.com/questions/38127616/python-nltk-cannot-import-mkdtemp) about running nltk on Windows with Anaconda, but this guy had a file called `tempfile.py` in his CWD. 

Looking at the traceback, this `"C:\Users\humph\Anaconda3\envs\yb\lib\tempfile.py"` seems suspicious, like it should be in `site-packages` and not `lib` -- but I'm not sure what it is or if that's even the problem. 

At this point, I might just buy myself a cheap windows laptop to test it myself!

**Pull request merged**
