### PR TITLE
Missing values

### LINKED ISSUE #1131: MissingValuesBar does not work on categorical columns
## Describe the solution you'd like
Currently, I am unable to get MissingValuesBar to work on data that has categorical columns. It is internally trying to convert these columns to a floating point value and producing an error at this step. I am hoping this can be handles internally in the class itself since it is just checking for missing values so it should not care about the type of column.

## Is your feature request related to a problem? Please describe.

Described above, but this is the error that I get on categorical data. One of the columns has continent values and it looks like it is producing an error at that point.

```python
# Instantiate the visualizer
plt.figure(figsize=(15,10))
visualizer = MissingValuesBar(features=features)

visualizer.fit(X=data[features], y=data[target].values) # Supply the targets via y
_ = visualizer.show() # Finalize and render the figure
```

**Traceback**
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-7-2b58032dfe22> in <module>
      3 visualizer = MissingValuesBar(features=features)
      4 
----> 5 visualizer.fit(X=data[features], y=data[target].values) # Supply the targets via y
      6 _ = visualizer.show() # Finalize and render the figure

~\.conda\envs\ds7337_cs3\lib\site-packages\yellowbrick\contrib\missing\base.py in fit(self, X, y, **kwargs)
     70         self.y = y
     71 
---> 72         self.draw(X, y, **kwargs)
     73         return self
     74 

~\.conda\envs\ds7337_cs3\lib\site-packages\yellowbrick\contrib\missing\bar.py in draw(self, X, y, **kwargs)
    137         target values.
    138         """
--> 139         nan_col_counts = self.get_nan_col_counts()
    140 
    141         # the x locations for the groups

~\.conda\envs\ds7337_cs3\lib\site-packages\yellowbrick\contrib\missing\bar.py in get_nan_col_counts(self, **kwargs)
    110 
    111         else:
--> 112             nan_matrix = self.X.astype(np.float)
    113 
    114         if self.y is None:

ValueError: could not convert string to float: 'euorpe'
```

**If I just take the numeric features, it works well**

```python
# Instantiate the visualizer
plt.figure(figsize=(15,10))
visualizer = MissingValuesBar(features=features_numerical)

visualizer.fit(X=data[features_numerical], y=data[target].values) # Supply the targets via y
_ = visualizer.show() # Finalize and render the figure
```

**See output below**

image

### PR DESCRIPTION
**Pull request by pdamodaran**
This PR fixes #1131.  The missing values visualizer errors out when a pandas data frame with string values is passed.  The fix also addresses cases when a column contains mixed data types and when columns contain boolean values.

I have made the following changes:

1. Updated missing values visualizer to handle multiple data types and work on both numpy arrays and pandas data frames.
2.  Added new tests to handle the above cases.

### TODOs and questions

Still to do:

- [x] The current implementation of the `fit` method does not account for a case when a numpy array is passed with no features defined.  There is a comment in the code that `super` should not be called.
- [x] I am running into an issue with the image comparison tests for the four new tests I added.  I have moved the actual images to the baseline images but I am still running into image comparison failures on the new tests.

Questions for the @DistrictDataLabs/team-oz-maintainers:

- [ ] What changes need to be made to the DataVisualizer and the Missing Values Visualizer in order to be added to the list of feature visualizers?

### CHECKLIST

- [x] _Is the commit message formatted correctly?_
- [ ] _Have you noted the new functionality/bugfix in the release notes of the next release?_

- [ ] _Included a sample plot to visually illustrate your changes?_
- [x] _Do all of your functions and methods have docstrings?_
- [x] _Have you added/updated unit tests where appropriate?_
- [x] _Have you updated the baseline images if necessary?_
- [x] _Have you run the unit tests using `pytest`?_
- [x] _Is your code style correct (are you using PEP8, pyflakes)?_
- [ ] _Have you documented your new feature/functionality in the docs?_

- [ ] _Have you built the docs using `make html`?_

### CODE REVIEW

**Comment by pdamodaran** [comment]
@bbengfort @lwgray - would appreciate guidance on the TODO items and the question I had regarding converting this to a FeatureVisualizer when you get a chance.

**Comment by lwgray** [comment]
@pdamodaran Great job with this.  I will give it a look soon!

**Comment by lwgray** [comment]
@pdamodaran I fixed the test.... your random choice was producing different visualizations each time so I used a scope specific seed generator to get reproducible results

**Comment by lwgray** [comment]
@pdamodaran In this statement, "The current implementation of the fit method does not account for a case when a numpy array is passed with no features defined. "  Are you saying that there isn't a check for an empty array?
@bbengfort Could you refactor the DataVisualizer?

**Comment by pdamodaran** [comment]
> @pdamodaran In this statement, "The current implementation of the fit method does not account for a case when a numpy array is passed with no features defined. " Are you saying that there isn't a check for an empty array?
> @bbengfort Could you refactor the DataVisualizer?

@lwgray - when the user does not define the features, we take care of it in the code by leveraging the columns in the array but this particular implementation does not do that, which results in an error.

@bbengfort - if you can let me know what needs to be done to refactor the DataVisualizer, I can take care of it.

**Comment by lwgray** [comment]
@pdamodaran Did you want to merge this PR as is and open separate issues for both the features bug and the Refactor?  We could label the features bug as "novice" and "good first contribution" or you could just fix the bug in this PR

**Comment by pdamodaran** [comment]
ok - I will make the update that will resolve the error for now and then create a separate issue to refactor the DataVisualizer.

**Comment by pdamodaran** [comment]
@lwgray - I have fixed the bug and added test cases.

**Review by lwgray — APPROVED** [review]
Wonderful job with covering all these edge cases and writing tests for them.

**Comment by bbengfort** [comment]
@pdamodaran @lwgray I guess I'll stay tuned for the refactoring issue to see what you mean.

**Comment by pdamodaran** [comment]
@bbengfort - The following is the comment in the `fit` method of the `MissingDataVisualizer` (https://github.com/DistrictDataLabs/yellowbrick/blob/develop/yellowbrick/contrib/missing/base.py)
```
       # Do not call super here - the data visualizer has been refactored
        # to provide increased functionality that is not yet compatible with
        # the current implementation. This mimicks the previous functionality.
        # TODO: Refactor MissingDataVisualizer to make use of new features.
```
We wanted to find out what changes we need to make to the `DataVisualizer` and the `MissingDataVisualizer` so that we can move these visualizers from `contrib` to `features`

**Comment by bbengfort** [comment]
@pdamodaran the data visualizer does quite a lot of work now, it does target type detection and colors the data with a `cmap` if the target is regression, or discrete colors if the target is classification. If either of the missing values visualizer want to take advantage of this target type detection, you'd probably have to do work to implement the colors functionality from the super class. If you didn't care about the target type, you could have the missing values visualizer subclass `MultiFeatureVisualizer` instead -- then you need to take care because that superclass handles data frames and numpy arrays to get the feature names; work that I think you did specifically for this class in this PR.

**Pull request merged**
