### PR TITLE
Fixed statsmodels incorrect import (code & doc)

### PR DESCRIPTION
**Pull request by ianozsvald**
After my recent code contribution I hadn't added the necessary `import` and the one used in the code was wrong (`statsmodels` has 2 ways of doing things). My colleague @robmarkcole fixed the code, I added a line 1 doc fix. The local test passes.

@DistrictDataLabs/team-oz-maintainers

### CODE REVIEW

**Comment by ianozsvald** [comment]
Should we have committed the 3 images?

**Comment by bbengfort** [comment]
No, you don't commit the `actual_images`, you should commit the `baseline_images` (`actual_images` is in tests/.gitignore) -- to sync actual with baseline run:

```
$ python -m tests.images tests/test_contrib/test_statsmodels/test_base.py
```

This should copy everything from `actual_images` to `baseline_images`.

**Comment by ianozsvald** [comment]
3 images removed and push, how do we look now?

**Comment by ianozsvald** [comment]
Much obliged to @robmarkcole for his addition, cheers both!

**Pull request merged**
