### PR TITLE
[WIP] Add tests for GridSearch Color Plot (towards #308)

### PR DESCRIPTION
**Pull request by souravsingh**
Fixes a small part of #308 by adding a test file. Test stubs need to be added.

### CODE REVIEW

**Comment by bbengfort** [comment]
@souravsingh just a quick note - don't worry about the CI tests failing, we will address it in #699; looking forward to the tests when you get a chance to do them!

**Comment by bbengfort** [comment]
@souravsingh I'm going to update your branch with the latest changes to see if that helps fix the CI issues we've been having. Any updates on this PR? Looks like some things are moving forward?

**Comment by bbengfort** [comment]
Please make sure you run `git pull` before making any more changes!

**Comment by rebeccabilbro** [comment]
Hi @souravsingh, since this conversation has gone a bit stale, I'm going to go ahead and archive this PR. Thanks for your interest in Yellowbrick and please feel free to re-open if/when you decide to begin working on this issue again!

**Pull request closed without merging**
