### PR TITLE
Issue 435 - Updated RankD tests.

### PR DESCRIPTION
**Pull request by mrdawson**
This PR addresses more of issue #435. Specifically, I made the following changes:
1.   Removed the make_regression function and updated the tests to use `yellowbrick.datasets` datasets
2.   Added tests for the `rank1d` and `rank2d` quick methods
3.   Extended the tests for `Rank1D` orientation

#### Questions:
To test the functionality of the various algorithms, I just followed what I had seen before and hard-coded the expected output matrices. Is this the preferred method?

The last point on #435 reads: "test the underlying rank matrix is correct." Could someone clarify what this means?

Thanks!

### CODE REVIEW

**Comment by mrdawson** [comment]
Also, the ImageComparisonTests were passing on my PC after I updated the images in the baseline images folder. It looks like they are failing the Travis CI check. Any guidance here would be appreciated.

**Comment by ndanielsen** [comment]
@mrdawson I'll take a closer look in the next day or so. Thanks for picking up this issue.

**Comment by ndanielsen** [comment]
hey @mrdawson make sure to pull down your latest branch when picking this up again.

**Comment by ndanielsen** [comment]
@mrdawson I think that figured out the issue. I think that on your local development env you might have matplotlib 2.x installed. The generated images are a bit different between 2.x and 3.x.

We recently got matplotlib 3.x working with out test suite thanks to the efforts of @nickpowersys 

Recommend that you:

1) Update your such as this: `pip install -U -r tests/requirements.txt`
2) Regenerate your images: `python -m tests.images tests/test_features/test_rankd`

When I pulled your branch, I got the same test failures as travis and appveyor. After I regenerated your images with matplotlib 3.x, I got the branch passing. 

Thanks for your efforts on this. Having a solid test suite allows our contributors to add cool stuff to yellowbrick with peace of mind that things are gonna work!

Let me know if you have any other questions!

**Comment by ndanielsen** [comment]
@mrdawson thanks for the effort on this. Sorry it's simply not working. I'm going to fork your branch and try myself tomorrow. Hopefully we can figure it out

**Comment by mrdawson** [comment]
@ndanielsen Thanks. I'll keep tinkering with it as well. I assume it's my local python environment. I'm running an Anaconda venv with Python 3.6. The packages all seem to match up with requirement.txt, but we'll see...

**Comment by ndanielsen** [comment]
@mrdawson still tinkering away on this myself. I'm not a `conda` user myself (I am slowly being won over through), so this might be a gap in our testsuite. 

As a bit of background, we are currently getting conda windows testing in order for windows, but don't seem have to it setup yet for our travis builds.  

When I did regenerate the images and get tests passing, it was within a `pyenv virtualenv`. So likely the different is conda vs virtualenv that is causing issue.

**Comment by mrdawson** [comment]
I've done a bit more digging. The ImageComparisonFailure only happens on the rank2d plots. The plots themselves are identical, but the colorbar label text is not quite the same (see the attached jupyter notebook pdf). The convention for image comparison tests seems to be to remove all labels. Should we just remove the colorbar text from plots like this as well?

[image_comparison.pdf](https://github.com/DistrictDataLabs/yellowbrick/files/3262877/image_comparison.pdf)

**Comment by ndanielsen** [comment]
@mrdawson I merged in the development branch to resolve some of the conflicts that popped up. As a result, I had to regenerate the rankd baseline images.

**Comment by rebeccabilbro** [comment]
Hey there @mrdawson &mdash; since it looks like the conversation has gone a bit stale here, I'm going to go ahead and archive this PR for now. Thanks again for checking out this issue and we'd love to have you work on Yellowbrick in the future! In case this is something you'd be game to revisit later, just a heads up that over the next couple weeks we are going to be pushing on some of the high-priority issues for our [v1.0 milestone](https://github.com/DistrictDataLabs/yellowbrick/milestone/13), which will reduce our bandwidth for reviewing non-milestone/non-bug related PRs, but should help accelerate our progress to v1.0! 🎉 Stay tuned!

**Pull request closed without merging**
