### PR TITLE
#295 

### PR DESCRIPTION
**Pull request by gary-mayfield**
ROC/AUC test images added to baseline_images

### CODE REVIEW

**Comment by bbengfort** [comment]
@gary-mayfield should we close #295?

**Comment by gary-mayfield** [comment]
Test ROCAUC with a binary classifier ... SKIP: binary classifiers don't currently work as expected
Test ROCAUC with classifiers that have a decision function ... SKIP: Not working with expected precision
Test ROCAUC with a multiclass classifier ... ok
Test ROCAUC with classifiers that have no scoring method ... ok
Test ROCAUC with classifiers that utilize predict_proba ... ok
Test ROCAUC with label encoding before scoring ... SKIP: Not implemented yet
Test ROCAUC without per-class curves ... ok
Test ROCAUC with no curves specified at all ... ok
Test ROCAUC without a macro average ... ok
Test ROCAUC without a macro or micro average ... ok
Test ROCAUC without a micro average ... ok
Test ROCAUC without label encoding before scoring ... SKIP: Not implemented yet
Test the ROCAUC quick method ... ok

This is what I'm getting if I run make test locally.

Apologies, I'm using a new machine and forgot to switch to branch. Can close #295 and continue with this one if that's ok?

**Comment by bbengfort** [comment]
Fixes #288 and #295

**Comment by bbengfort** [comment]
@gary-mayfield ok, so at this point you may want to delete all your branches and then pull from upstream master so that you're syncrhonized - I notice there were a couple of spare commits from your other PR in this one.

**Comment by bbengfort** [comment]
Sorry didn't mean to criticize, was just trying to help out. See [syncing a fork](https://help.github.com/articles/syncing-a-fork/) for more details. Basically, your fork is `origin` and district data labs is `upstream` -- you can keep track of them more easily that way.

**Pull request merged**
