### PR TITLE
Roc/auc

### PR DESCRIPTION
**Pull request by gary-mayfield**
before
after

Above shows before and after on running example from #288 

A number of the tests are failing with ImageComparisonFailures as well which I'm attempting to figure out.

Also:

            self._module_path =  full_path.split('yellowbrick')[1].split('/')[2:]

this line in tests\base.py needs to be below for them to run on my Windows machine

            self._module_path =  full_path.split('yellowbrick')[1].split('\\')[2:]

### CODE REVIEW

**Comment by gary-mayfield** [comment]
Also if anyone has any advice on why my previous merged commits are showing in this pull request I'd appreciate it.

**Comment by NealHumphrey** [comment]
@gary-mayfield re: why your commits are showing up on this PR. 

My guess is that the "squash and merge" option was used on Github to merge your `@property` pull request in. You can see this as the #161 commit in the screenshot below, which contains all the changes in your other commits. But using the 'squash and merge' option makes a new commit, so the old commits are still there. 

If you look on this pull request, you'll see that the files changed tab doesn't show any of the changes from those older commits b/c they've been incorporated with that extra single squash and merge commit, but that squash and merge commit was put directly into the develop branch. 

I'm not totally sure of how to avoid this, but per the 'files changed' tab it looks like this PR does have what you expect it to. 

image

**Comment by gary-mayfield** [comment]
Thanks @NealHumphrey for taking the time to respond.

 I just want to make sure I'm not causing any issues with the way I'm committing my changes.

**Comment by bbengfort** [comment]
@gary-mayfield sorry it's taken me so long to get back to this with the holidays. Looks like you and @NealHumphrey confirmed that the merge is correct so it's time to review. 

The changes did cause the tests to fail with `image not close` errors -- which is perfectly fine since you did, in fact, change the code. This is probably a good time to explain the image testing system - 
 you can find documentation about that at [image comparison tests](http://www.scikit-yb.org/en/develop/contributing.html#image-comparison-tests). 

Basically, in the tests directory you should see two subdirectories: `actual_images` and `baseline_images`. Both of these directories are structured similarly to the test structure; e.g. `test_classifier/test_rocauc` will contain the test images for ROCAUC. The `baseline_images` directory contains the expected images, and the `actual_images` contains the images that were generated during tests. 

Would you mind posting to this thread the images in your `tests/actual_images/test_classifier/test_rocauc` after you run `make test`? Specifically the following files:

- test_rocauc_no_micro.png
- test_rocauc_no_macro.png
- test_rocauc_no_classes.png 

These are the tests that failed. Alternatively, you could copy these images from `actual_images` to `baseline_images` and commit and we could review them in the commit. @ndanielsen could you let @gary-mayfield know how to see the diffs?

**Comment by gary-mayfield** [comment]
test_rocauc_no_micro
test_rocauc_no_macro
test_rocauc_no_classes


Hi @bbengfort 

As requested, please find attached the requested images.

**Comment by bbengfort** [comment]
@gary-mayfield ok - these look good, if you replace them in `baseline_images` the tests should pass, then we can merge the PR.

**Comment by bbengfort** [comment]
See #298

**Pull request closed without merging**
