### PR TITLE
Yellowbrick Test Using Regression Models

### PR DESCRIPTION
**Pull request by pbwitt**

### CODE REVIEW

**Comment by bbengfort** [comment]
@pbwitt thanks for submitting a pull request! We'll be reviewing it this afternoon.

**Comment by pbwitt** [comment]
@bbengfort  Sorry about that.  I deleted the unnecessary files.  There were 5 datasets included from the UCI repo. I only used the first but left the others in.  In addition, I deleted the arff files. Please let me know if the size is acceptable now.  If not I will delete the data folder.

**Comment by bbengfort** [comment]
@pbwitt no problem at all, it wasn't a mistake, but thanks for cleaning up the data directory! I've approved the changes and will merge the pull request. Thanks again!

**Comment by pbwitt** [comment]
@bbengfort   good news!   Please let me know if there is anything else you need help testing.

**Pull request merged**
