### PR TITLE
adding explanation for the confusion matrix example

### PR DESCRIPTION
**Pull request by mohfadhil**
I found that 'confusion matrix' example in the example.ipynb does not have an explanation. what is it and how useful to the data science project.

### CODE REVIEW

**Comment by ndanielsen** [comment]
@mohfadhil thanks for raising this issue, we'll try to get back to you and respond in the next week or so

**Comment by mohfadhil** [comment]
Yes sure, I did modify the text.

**Comment by Kautumn06** [comment]
Thank you @mohfadhil for contributing to Yellowbrick! I'll review the updates and let you know if I have any questions or feedback.

We'd be delighted to have you contribute again, so please feel free to checkout any of our other open [issues](https://github.com/DistrictDataLabs/yellowbrick/issues). We've labeled many of them with expertise levels and have some marked for [hacktoberfest](https://github.com/DistrictDataLabs/yellowbrick/issues?q=is%3Aopen+is%3Aissue+label%3Ahacktoberfest) as well.

**Comment by bbengfort** [comment]
@Kautumn06 feel free to squash and merge this when you approve it.

**Pull request merged**
