### PR TITLE
Add: add image similarity test for locate_elbow in the KElbowVisualiz…

### PR DESCRIPTION
**Pull request by ndanielsen**
Adding a basic image similar test for when `locate_elbow=True` in the scenario below.

```
        visualizer = KElbowVisualizer(
            KMeans(random_state=0), k=5,
            metric="calinski_harabaz", timings=False, locate_elbow=True
        )
```
The elbow score is already stripped out in the image similarity test suite, but it's a good thing to be sure of. =)

### CODE REVIEW

**Comment by ndanielsen** [comment]
Related to this PR:

https://github.com/DistrictDataLabs/yellowbrick/pull/824

**Comment by pdamodaran** [comment]
Hi @ndanielsen  - thanks for adding this test!  It is good to be sure as we add new features that we can ensure that the image comparison tests still work.  One thing I believe that this test will also benefit from is if you could add one additional test to check the self.elbow_value_ as none of the tests currently have it and this is a value that would get populated when `locate_elbow=True` is set.

**Comment by ndanielsen** [comment]
@pdamodaran made requested changes. Great code review btw!

**Comment by pdamodaran** [comment]
@ndanielsen - thanks for adding the PR to get the AppVeyor build to pass.  I will go ahead and merge this in.

**Pull request merged**
