### PR TITLE
Add Kendall-tau metric

### PR DESCRIPTION
**Pull request by souravsingh**
Continuation of #621

### CODE REVIEW

**Comment by ndanielsen** [comment]
@souravsingh thanks for picking this up. I'm glad to see it and thank you for your contribution.

In order for me to continue my review of this, can you kindly add some test coverage on this? You can find information on our approach to testing in the [contributor documentation. ](http://www.scikit-yb.org/en/latest/contributing.html)

**Comment by souravsingh** [comment]
@bbengfort Do we need to make the kendall-tau method private for the rankd module, so it can be imported when using `import *`?

**Comment by bbengfort** [comment]
@souravsingh - if you mean add it to the `__all__` variable on Line 30 so it can be imported when using `import *` - I'd actually prefer if we didn't do that, this isn't a function that our users are going to want to import from us, they'll be looking for the visualizer. 

In the tests, you should be able to import the function using:

```python
from yellowbrick.features.rankd import kendalltau
```

Even though it's not in `__all__`, if you directly specify it. Let me know if you're still having problems.

**Comment by bbengfort** [comment]
@souravsingh glad to see you're still pushing commits on this - let me know if you have any questions so we can get it to the end!

**Comment by souravsingh** [comment]
@bbengfort Can you take a look at the recent changes and give your review?

**Comment by souravsingh** [comment]
@bbengfort Thanks for helping with the PR. I look forward to contributing to the project even more.

**Comment by bbengfort** [comment]
@souravsingh that would be great; looking forward to more PRs!

**Pull request merged**
