### PR TITLE
Addresses Issue #615 : Adding new parameters "Colorbar" and "Heatmap" in PCA visualizer

### PR DESCRIPTION
**Pull request by percygautam**
The following changes were made to` pca.py` referenced in #615 :

- Added new optional parameters 'Colorbar' and 'Heatmap' which shows the magnitude of each feature value to the component, for both '2D' and '3D' cases.

Next Step:

- Updating Documentation with a proper explanation on how to use these two optional parameters when using PCA visualizer.

P.S: I am adding a snippet showing PCA visualization of the dataset `credit` from yellowbrick.datasets, when both the parameters are True and proj_dim = 2.

PCA

### CODE REVIEW

**Comment by rebeccabilbro** [comment]
Hey there @percygautam and thanks for checking out Yellowbrick! We [recently merged in a PR](https://github.com/DistrictDataLabs/yellowbrick/pull/811) that also touched `yellowbrick/features/pca.py`, so before we proceed with the review, we'll need to resolve the conflicts in that file. Are you up for taking a crack at pulling from `develop`, resolving any conflicts on your machine, and pushing the updates to this same branch? Let us know if you have any questions!

**Comment by percygautam** [comment]
@rebeccabilbro  I am working on resolving the conflicts due to the recently merged PR.

**Comment by percygautam** [comment]
@rebeccabilbro I have resolved the conflict raised by the recent PR. Heatmap and Colorbar, as well as alpha parameter, are working fine in my machine

**Comment by percygautam** [comment]
Kon'nichiwa! @rebeccabilbro 
I understand the problem and the importance of having a separate private method for dividing the axis.
I'll get right into solving this problem. 
I'll keep in touch about the progress.

**Comment by rebeccabilbro** [comment]
Hey there @percygautam! Is this still something you're planning to work on?

**Comment by percygautam** [comment]
Hey there, I didn't get the time to work because of my semester examinations. Now that they are over, I'll continue to work on the task at hand. Will try to make a submission by next weekend.

**Comment by rebeccabilbro** [comment]
Ok great, looking forward to it!

**Comment by rebeccabilbro** [comment]
Hi again @percygautam &mdash; since it looks like the conversation here has gone a bit stale, I'm going to go ahead and archive this PR for now. If you end up having time to come back to this, feel free to re-open this PR or open a new one, and thanks again for checking out Yellowbrick!

**Comment by percygautam** [comment]
@rebeccabilbro  I have updated the files as you have advised. Should I re-open the PR or  make a new one?

**Comment by rebeccabilbro** [comment]
Hey there @percygautam! So glad to have you working on this! Since the current edits touch only one file,  it should be safe to reopen this PR (though we'd pretty quickly need to do a pull from `develop` to make sure you have all the most recent changes, which can sometimes get a little tangly). Alternatively, if your `develop` branch is synced with ours, it might be easiest to open a new feature branch off of that and cut a new PR with your changes to `pca.py`. Either way, look forward to seeing this contribution!

**Pull request closed without merging**
