### PR TITLE
Translation of CONTRIBUTION.md, README.md, DESCRIPTION.md and some of…

### PR DESCRIPTION
**Pull request by NikoT98**
… the docs

This PR fixes #issue_number _(If you are fixing a bug)_ which reported a bug that caused a problem to occur when users...

_(or if you are introducing a new feature)_ which requested a feature to allow the user to...

I have made the following changes:

1.
2.
3.

### Sample Code and Plot

_If you are adding or modifying a visualizer, PLEASE include a sample plot here along with the code you used to generate it._

### TODOs and questions

Still to do:

- [ ]
- [ ]
- [ ]

Questions for the @DistrictDataLabs/team-oz-maintainers:

- [ ]
- [ ]

### CHECKLIST

- [ ] _Is the commit message formatted correctly?_
- [ ] _Have you noted the new functionality/bugfix in the release notes of the next release?_

- [ ] _Included a sample plot to visually illustrate your changes?_
- [ ] _Do all of your functions and methods have docstrings?_
- [ ] _Have you added/updated unit tests where appropriate?_
- [ ] _Have you updated the baseline images if necessary?_
- [ ] _Have you run the unit tests using `pytest`?_
- [ ] _Is your code style correct (are you using PEP8, pyflakes)?_
- [ ] _Have you documented your new feature/functionality in the docs?_

- [ ] _Have you built the docs using `make html` (must be run from `docs/`)?_

### CODE REVIEW

**Comment by rebeccabilbro** [comment]
Grand merci @NikoT98!  This is an incredibly generous contribution to Yellowbrick, and I am so excited to make your translation available to the Yellowbrick community. 

One question -- Would you be open to me moving your translation into [a new repository](https://github.com/DistrictDataLabs/yellowbrick-docs-fr) created (5 minutes ago 😅 ) specifically for the French documentation?  We did something similar with [Spanish](https://github.com/DistrictDataLabs/yellowbrick-docs-es) last year, which allowed us to create this new [Spanish language version in ReadTheDocs](https://www.scikit-yb.org/es/latest/).

Based on your preference, I can either open a new PR into that repo with your commits and credit you with the translation, or you could open the PR directly into that repo. 

Please let me know your preference, and again, merci mille fois for your thoughtful translation and your excellent PR!

**Comment by NikoT98** [comment]
Thank you for your email.

It's with great pleasure that I am contributing to Yellowbrick !

That would be awesome if you could open the PR into the French repository :)

Best regards.
Nicola

**Comment by bbengfort** [comment]
Hi Nicola,

Excellent, thank you so much; I'll get to that as soon as possible!

Best Regards,
Benjamin Bengfort
*mens divinior*

**Comment by rebeccabilbro** [comment]
...et voilà @NikoT98 !! 🎉 

Here's the [repo](https://github.com/DistrictDataLabs/yellowbrick-docs-fr) and the [brand-new deployed docs en français](https://www.scikit-yb.org/fr/latest/index.html) on ReadTheDocs. 

J'espère qu'ils vous vont bien 🤩  Je fermerai celui ci et si vous avez des ajouts, vous pouvez les ajouter au nouveau repo, d'acc ? Je vous remercie 🙏 encore pour votre contribution 🙌  extrêmement généreuse!

**Pull request closed without merging**
