### PR TITLE
Add DBCV Under Clustering

### LINKED ISSUE #229: Density based clustering validity measures
Clustering scores like silhouette work well for K-Means but make less sense for density based clustering techniques like DBSCAN which support arbitrary cluster shapes. It would be nice to include scores and visualisation for measures that support density based notions of clustering. These are a a little thin on the ground, but the Density Based Cluster Validity Index of Moulavi et al (http://www.dbs.ifi.lmu.de/~zimek/publications/SDM2014/DBCV.pdf) is one of the better ones.

### PR DESCRIPTION
**Pull request by lwileczek**
# Density-Based Clustering Validation
This feature is good for checking the validity of clustering algorithms such as DBSCAN or OPTICS.
This PR fixes #229 which is centered around adding support for Density-based clustering algorithms. 

### Changes
I have made the following changes    
1.  Added dbcv.py under [cluster](https://github.com/lwileczek/yellowbrick/tree/develop/yellowbrick/cluster)

I'm just initializing the effort.

### ToDo
- [ ]  Write out all 8 functions described in [DBCV](http://www.dbs.ifi.lmu.de/~zimek/publications/SDM2014/DBCV.pdf) paper
- [ ]  Add docstring for each function
- [ ]  Test on DBSCAN example
- [ ]  Test on OPTICS example
- [ ]  Update any required Document pages
- [ ] check PEP8 

### Questions for the @DistrictDataLabs/team-oz-maintainers:
- [ ]  Should this be added to [elbow.py](https://github.com/DistrictDataLabs/yellowbrick/blob/develop/yellowbrick/cluster/elbow.py#L43) under distortion instead of its own file?   
- [ ]  Should I add in other features for turning density-based clustering methods in this ticket or would that be a new PR?  This ticket is to support Density-based models as a whole. To help tune DBSCAN it's popular to find how _dense_ the data is to help pick an epsilon, or neighborhood size, when running the algorithm. [See here](https://www.datanovia.com/en/lessons/dbscan-density-based-clustering-essentials/#method-for-determining-the-optimal-eps-value)

### CODE REVIEW

**Comment by lwgray** [comment]
Just wanted to say hi and thank you for posting a PR.  We are away at PyCon at the moment but We will follow up with a response to your questions asap.

**Comment by bbengfort** [comment]
Hi @lwileczek - thank you so much for opening up this PR and taking on the density based metrics! I think that you're exactly on the right path; opening the PR early with a stub file and describing how you will proceed. We find that this approach leads to the most successful PRs! Your TODO list is perfect and complete, thank you for outlining such a straight forward path! I'm also very excited to get some new clustering metrics into YB; this is one of our value adds to scikit-learn and I think this will be a top-notch contribution! 

I only have one note that will perhaps make things a bit easier if this PR takes a while to complete. The PR you created is from the `develop` branch of your fork into our `develop` branch, which is perfectly fine. However, it may make things easier for you if you open a PR from a feature branch instead. This will allow you to more easily synchronize changes with our upstream fork without creating merge conflicts. Instructions to do this is at our [contriburtor's guide](https://www.scikit-yb.org/en/latest/contributing.html#forking-the-repository) as well as other helpful tips. This will cause you to have to close and reopen the PR, unfortunately, so if you're not confident with git or not planning on contributing to yellowbrick in the future, we could just skip it and proceed from here. Please let me know if you have any questions! 

To answer your questions:

I think that you're on the right path with this file right now; I can see these metrics being used in both the `KElbowVisualizer`, the `SilhouetteVisualizer`, and the `ICDM` - therefore adding it as a general utility library in `yellowbrick.cluster.dbcv` makes perfect sense. Once we see how the module shapes up and we compare it to other metrics in the clustering library, we can discuss making a more general utils library if needed; but it's perfect where it is for right now! 

My sense is that the PRs should focus on only one thing, there is a lot to do to implement DBCV and we want to get this merged! My recommendation is that we create another issue for tuning density-based clustering and reference #229 and this PR. 

The tests are failing because our style checker is complaining about ["Unused Imports"](https://travis-ci.com/DistrictDataLabs/yellowbrick/jobs/197682774#L1326) - but please don't worry about this too much; we'll make sure the tests are sorted out before we merge the PR. 

Thanks again, and looking forward to seeing more!

**Comment by rebeccabilbro** [comment]
Hey there @lwileczek! Were you still planning to work on this?

**Comment by lwileczek** [comment]
Hello yes! Sorry I have been traveling a lot recently. I am going to remove this pull request and start a feature branch. I need to re-read the paper but should be able to have significant progress next weekend over Memorial Day weekend

**Comment by rebeccabilbro** [comment]
> Hello yes! Sorry I have been traveling a lot recently. I am going to remove this pull request and start a feature branch. I need to re-read the paper but should be able to have significant progress next weekend over Memorial Day weekend

Ok, thanks for the update @lwileczek and looking forward to it!

**Pull request closed without merging**
