### PR TITLE
Add Kendall-Tau correlation measure

### PR DESCRIPTION
**Pull request by souravsingh**
Fixes a part of #68 by adding Kendall-Tau measure to Rank2D

### CODE REVIEW

**Comment by rebeccabilbro** [comment]
Hello @souravsingh and thanks for the PR! It would be wonderful to be able to offer more options for the Rank2D plots! looks like our automated tests are having a little trouble right now (nothing to do with your commits; it looks like it might be due to the newest Matplotlib); give me a little time to see if I can sort those out (which will probably just result in me upping the tolerance levels for the visual comparison tests that are currently failing), and then we'll get your PR reviewed, sound good?

**Comment by souravsingh** [comment]
Sounds good to me @rebeccabilbro. Looking forward to contributing even more to Yellowbrick.

**Comment by bbengfort** [comment]
@souravsingh also, please make sure to pull before you start work, we merged the changes that fixed the tests!

**Comment by souravsingh** [comment]
Thanks for the review @bbengfort. I will look into it and add the fixes.

**Comment by rebeccabilbro** [comment]
Hello @souravsingh - just wanted to check in to see if this was still something you wanted to work on? Let us know if there's anything we can help with!

**Comment by rebeccabilbro** [comment]
Hi there @souravsingh - just wanted to check to see if this was something you still wanted to work on? We maintainers try to keep our PR dialogues from going stale, since they have an expiration date after a few weeks without updates. Let us know if there's anything you need from us to help move forward!

**Comment by rebeccabilbro** [comment]
Hi again @souravsingh - going to go ahead and close this one out per the discussion above, but if you decide to come back to this later, feel free to reopen and push more commits to the same branch!

**Comment by souravsingh** [comment]
Sorry for keeping the conversation quiet @rebeccabilbro. I have made a new PR with the required changes.

**Pull request closed without merging**
