### PR TITLE
Implement black code formatting as pre-commit hook

### LINKED ISSUE #456: Implement black code formatting as pre-commit
In order to avoid style-related comments when discussing code with contributors, I propose that we implement the [black](https://github.com/ambv/black) python code formatter as a pre-commit requirement for development. 

This will potentially have a large impact on our current code-base, so should be undertaken right before a release to ensure that we don't end up with large merge conflicts. Also for discussion:

- what styles do we want to customize with black? 
- is black in its beta stage stable enough to use with our project?
- do we set this up as a pre-commit in GitHub/Travis/locally?

### PR DESCRIPTION
**Pull request by stefmolin**
This PR fixes #456 which requested a pre-commit hook for `black`.

I have made the following changes:

1. Added `.pre-commit-config.yaml` to configure pre-commit hooks.

### Setup and Examples

Since we are deciding how best to have people set up the hook, here is an example of how to do so with the YAML file included in the first commit:

```shell
pip install pre-commit
pre-commit install      # run this from the yellowbrick folder after checking out this branch
```

To start with, I have provided the following hooks:
- removal of trailing whitespace
- fix end of file
- check that the YAML for the config is valid
- check that the commit won't be adding large files
- run `black`

The pre-commit hooks run automatically once you run `git commit`. Note that you don't have to install `black` because the first time you run this, `pre-commit` will build a testing environment for the staged changes (it pulls down the version of `black` specified in the YAML for you). I installed the hook before making the commits here; below is the output of my first commit:
```
$ git add .pre-commit-config.yaml 
$ git commit -m "Add .pre-commit-config.yaml with black."
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Initializing environment for https://github.com/psf/black.
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/psf/black.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
Trim Trailing Whitespace.................................................Passed
Fix End of Files.........................................................Passed
Check Yaml...............................................................Passed
Check for added large files..............................................Passed
black................................................(no files to check)Skipped
[feature-pre_commit_config 622c818] Add .pre-commit-config.yaml with black.
 1 file changed, 14 insertions(+)
 create mode 100644 .pre-commit-config.yaml
```

Please note that you can bypass `pre-commit` hooks by running `git commit -m "Your commit message" --no-verify`.

You can use also use `pre-commit` on specific files even if you haven't changed them yet (i.e., you have nothing to commit yet):
```shell
pre-commit run --files yellowbrick/anscombe.py
```
Screen Shot 2022-07-29 at 7 55 27 PM

More information and options can be found in the [pre-commit docs](https://pre-commit.com/).

### TODOs and questions

Still to do:

- [x] Add setup information to contributing docs.
- [x] Potentially update `requirements.txt` files (based on discussion with maintainers).
- [x] Add other checks mentioned in comments.
- [x] Incorporate flake8 checks.
- [x] Add black badge
- [x] Look into incorporating as a GitHub Action.

Questions for the @DistrictDataLabs/team-oz-maintainers:

- [x] After experimenting with this and reviewing #456, do you want to include the `pip install` and `pre-commit` install commands in the contributors doc only? Or do you want to put `pre-commit` in the `requirements.txt` file also (note that contributors will still need to run the `pre-commit install` command)?
- [x] If we are going to add `pre-commit` to the `requirements.txt`, which one would be appropriate &ndash; I see there are a few?
- [x] Are there any other checks you would like to include?
- [x] Do you want to include the `black` badge in the README? (You can see it on the `black` README, if you aren't sure what it looks like).

### CHECKLIST

- [X] _Is the commit message formatted correctly?_
- [ ] _Have you noted the new functionality/bugfix in the release notes of the next release?_

- [x] _Have you documented your new feature/functionality in the docs?_

- [x] _Have you built the docs using `make html`?_

### CODE REVIEW

**Comment by stefmolin** [comment]
CC @bbengfort

**Comment by stefmolin** [comment]
@bbengfort - have you had a chance to try this out?

**Comment by bbengfort** [comment]
@stefmolin thanks for checking back in -- unfortunately, I haven't had a chance to take a look until just now; I was on holiday last week and it's been a busy week catching up again; so I definitely appreciate you're bumping this back to the top of my attention! 

It looks like this is pretty straightforward - it's just an additional configuration in the repo; if contributors install `pre-commit` then this will run, but if they don't, then the configuration file is ignored. I think this is a really good compromise because the routine contributors can use it to check their work but it won't block newcomers from making contribs. 

Based on this idea, I propose the following answers to your questions:

1. Let's include the `pip install` and `pre-commit` install commands in the contributors doc and add a commented-out line with the version in `requirements.txt`; e.g. similar to the [optional dependencies](https://github.com/DistrictDataLabs/yellowbrick/blob/develop/requirements.txt#L8) comment in that file. That will ensure contributors will install the correct version of `pre-commit` but make it optional.
2. I assume the list of hooks is here: https://pre-commit.com/hooks.html? I've added a few that I think would be good below.
3. Sure, I'm happy to add a black badge to the README if you think that would be helpful. 

Other useful checks:

- `check-json` (our data files for downloading datasets are in json)
- `check-merge-conflict` (I was surprised at how often this happens)
- `rst-backticks`, `rst-directive-colons`, and `rst-inline-touching-normal` would helps with docs
- `gitleaks` could be useful, though I'm not sure how well it works 

Could we also add a [GitHub Action](https://pre-commit.com/#usage-in-continuous-integration) check for `pre-commit` this would not be a required check for merging but would signal to the maintainers that code is correctly formatted in a PR. 

Thank you so much for taking this issue on and for your thoughtful and complete PR!

**Review by bbengfort — COMMENTED** [review]
Looks good so far, thank you again for your thoughtful method of proceeding with this PR!

**Comment by stefmolin** [comment]
Thanks for the feedback @bbengfort &ndash; I hope the holiday was restorative! I'll update with the additional checks you added. I have not used the `gitleaks` one, so I can't speak to its effectiveness; however, I think as a general rule you don't want to add too many checks either as they run in series and each one will add a little bit of time to execute. I also noticed that you have `flake8` in your [setup.cfg](https://github.com/DistrictDataLabs/yellowbrick/blob/develop/setup.cfg#L32-L38), so I will add that as well.

> Sure, I'm happy to add a black badge to the README if you think that would be helpful.

I think it's nice to let potential contributors know what they can expect as far as coding standards you follow. If it helps you decide, [scikit-learn](https://github.com/scikit-learn/scikit-learn/tree/main) has the badge in their README.

> Could we also add a [GitHub Action](https://pre-commit.com/#usage-in-continuous-integration) check for pre-commit this would not be a required check for merging but would signal to the maintainers that code is correctly formatted in a PR.

I haven't tried this personally, but I will take a look.

**Comment by bbengfort** [comment]
It was restorative thank you! If you think we shouldn't add extra checks then let's skip `gitleaks`; thanks for adding `flake8`!

**Comment by stefmolin** [comment]
I took a look at `gitleaks`, and you will either need to have Go or Docker installed, so there is a bit of overhead on that one &ndash; I left it off for now. To add `flake8`, I also had to update the `flake8` config in `setup.cfg`, so that it would be compatible with `black` (more info [here](https://black.readthedocs.io/en/stable/guides/using_black_with_other_tools.html#flake8)).

I updated the contributing docs and the `requirements.txt` file &ndash; let me know if those need any changes.

I'm going to experiment with the GitHub Action in my fork. Other than that, the only remaining thing is the `black` badge to the README: have you decided whether you want to include it?

**Comment by stefmolin** [comment]
I got the hooks working in GitHub actions. I set it to only look at files that changed in the PR, which made it much more difficult to configure, but otherwise, I imagine every PR would fail the check until every file was cleaned up :smile:

You can see that the CI check for "Linting" was performed for this PR, and it ran the checks for everything but JSON and Python files (output [here](https://github.com/DistrictDataLabs/yellowbrick/runs/7816375876?check_suite_focus=true)) since there weren't any of those files here. To test, I purposely introduced some formatting issues in a file for `black` to find in my fork: you can see the results of that test (which fails since it finds those issues) [here](https://github.com/DistrictDataLabs/yellowbrick/runs/7816375876?check_suite_focus=true).

**Review by bbengfort — APPROVED** [review]
I'm very excited to close a four year old issue! #456 has always seemed like a good idea and we simply never got around to it -- which is what makes your PR so valuable, it feels like a boost just where we needed it and only you could have provided it! Thank you again so much for your PR and for the extremely thoughtful and well communicated design, implementation, and review process. I know making changes to an existing code base can be tricky but you made it look easy, which to me just demonstrates how excellent your approach is! 

The GitHub actions look great and I think the trickier configuration is going to be well worth it. You're right that PRs in Yellowbrick get complicated because image comparison tests from a different module may break your PR and this is just one less thing to worry about! 

The black badge looks great!

Don't worry about including an entry in the changelog -- @lwgray and I will be releasing the next version soon and we will update the changelog with your contribution then. 

I think there is just one last thing - would you mind sync'ing with `develop`? For some reason I don't seem to have the ability to do it on the PR; once sync'd we'll get this merged in ASAP. 

Well done and thank you again!

**Comment by bbengfort** [comment]
@stefmolin never mind - I was able to get the PR merged in; no need to sync to `develop`!

**Comment by bbengfort** [comment]
@stefmolin oops, the linting GitHub actions check failed when I merged into `develop` :-) -- I know you included failures to demonstrate how the GitHub action worked; did I merge prematurely? 

https://github.com/DistrictDataLabs/yellowbrick/runs/7878847521?check_suite_focus=true

**Comment by stefmolin** [comment]
@bbengfort - I'm happy I was able to help! It wasn't a premature merge, as those tests where in a separate branch in my fork. I think I know what is going on: the additional logic is to perform a diff across branches in a PR, but merging a branch in won't have those fields pulled in with the GitHub Actions. I'm learning about how to configure these actions through this PR, so it's a learning experience for me as well 😄 

The linting test should only run on PRs, which I believe needs a separate workflow config. I will put in a new PR for that.

This brings up another question though: do you want to perform the linting checks on the whole repo upon merging? We can also add a badge to the README that displays whether the code base is currently passing the linting checks.

**Comment by stefmolin** [comment]
@bbengfort - Thanks for the quick response. I will put in a PR for these changes then :smile:

**Comment by stefmolin** [comment]
@bbengfort - I implemented the changes discussed in https://github.com/DistrictDataLabs/yellowbrick/pull/1276.

**Pull request merged**
