### PR TITLE
Added Demo for effect plots in python

### PR DESCRIPTION
**Pull request by pswaldia**
In reference to #604 , I have added a simple example showing how the effect plot will work according to the blog post linked with the issue . Linear Regression is being performed on a simple housing data containing one numerical feature (size) and one ordinal feature (No. of rooms) . It is done to just demonstrate before proceeding to actual implementation of visualizer. Please review and guide me on how to proceed further.

### CODE REVIEW

**Comment by lwgray** [comment]
@pswaldia thank you for putting this together.  We are really excited by your progress.  However, we are a bit busy over the next 2 weeks and can fully review it afterwards.  In the meantime if you wanted to read more about implementing a visualizer, checkout our contributors guide.  http://scikit-yb.org/en/latest/contributing.html

**Comment by pswaldia** [comment]
Ok, i will read that.

**Comment by pswaldia** [comment]
I have read the contributions guide and over these 2 weeks explored yellowbricks visualizer api. I want to frame a proposal for gsoc and wanted some guidance. I want to work towards creating an effect plot visualizer in yellobricks. Whom should i contact?

**Comment by wagner2010** [comment]
Hi @pswaldia.  Thanks so much for your interest in Yellowbrick and gsoc.  As I’m sure you know, today (3/25) is the first day of the student application period for GSOC (through April 9).  That’s great that you read the contributor guide and have been through our docs.  I suggest using those guidelines in your proposal (the format).  The best way to interact with us is through our GitHub repo.  We have a number of issues there (including the one you flagged).  Feel free to work PRs or even pieces of PRs pertaining to existing issues (and feel free to tie it in to your proposal).  After the student period closes on April 9 we have about 3 weeks to review proposals and select.  We are having a small GSOC footprint this year due to our inaugural year but regardless of outcome we definitely welcome your engagement.  Follow us on Twitter (@scikit-yb) and star this repo if you haven’t!  We’ll see you online.  Stay well!-Adam

**Comment by rebeccabilbro** [comment]
Hey there @pswaldia  &mdash; your notebook looks like a good start. If you'd still like to move forward with working on this PR, the next step is to push some code so that we can see how you will implement the `EffectsPlot` under the Yellowbrick API. Per @bbengfort's advice [here](https://github.com/DistrictDataLabs/yellowbrick/issues/604#issuecomment-429552820), this visualizer belongs in the `regressors` module.

Please note that if you would like to add example notebooks, you should only do so inside a new folder inside our examples directory, named after your Github username (`yellowbrick/examples/pswaldia`). Your example notebooks should not be pushed to the top level directory, and no data should be pushed to the Yellowbrick codebase. If you would like to suggest a new dataset for inclusion, please open a pull request in the [`yellowbrick-datasets` repo](https://github.com/DistrictDataLabs/yellowbrick-datasets).

**Comment by rebeccabilbro** [comment]
Hey there @pswaldia &mdash; since the conversation in this PR has gone a bit stale, I'm going to go ahead and close it. Please feel free to reopen if you decide to come back to working on this and thanks for your interest in Yellowbrick!

**Pull request closed without merging**
