### PR TITLE
BUG: Fixes axes limit for PredictionError plot #1193

### PR DESCRIPTION
**Pull request by pkaf**
This fixes Issue #1193. X and Y axis limits are synced and set to overall max/min values of (X, Y).

Screen Shot 2022-01-20 at 9 16 58 am

### CODE REVIEW

**Comment by bbengfort** [comment]
@pkaf thank you again for contributing to Yellowbrick! Since this is a pretty simple change; I think this will work well - the tests are failing because the baseline images are now incorrect; I'm going to regenerate the images and spot-check a few of them. I'll let you know when I do so that you can also view the new baseline images. Note that this means I need write access to your fork - I'll let you know if you need to do anything extra.

**Review by bbengfort — COMMENTED** [review]
@pkaf I re-ran the baseline images and everything looks ok; one test is still failing: [test_peplot_no_shared_limits](https://github.com/DistrictDataLabs/yellowbrick/blob/develop/tests/test_regressor/test_prediction_error.py#L166) - which asserts that the axes are different based on a user kwarg. This zoom method ensures the aspect ratio is square, should we remove the `shared_limits` kwarg and references to that kwarg in the code? Is it still valuable? Is there a way to change the test so that it will pass?

**Comment by pkaf** [comment]
@bbengfort may be the _shared_limits_ is worth keeping with True as a default value. With following code modification inside the draw function?
```python
self.ax.set_xlim(min(min(y), min(y_pred)), max(max(y), max(y_pred)))
self.ax.set_ylim(self.ax.get_xlim())
 ```
 to 
 ```python
if self.shared_limits == False:
    self.ax.set_xlim(min(y), max(y))
    self.ax.set_ylim(min(y_pred), max(y_pred))
else:
    self.ax.set_xlim(min(min(y), min(y_pred)), max(max(y), max(y_pred)))
    self.ax.set_ylim(self.ax.get_xlim())
 ```
 This will make the current test in-place still relevant. Suggestion?

**Comment by bbengfort** [comment]
@pkaf that works for me - looks like the tests are passing; I'll handle the merge conflicts and we'll get this merged! Thanks again for your patience.

**Review by bbengfort — APPROVED** [review]

**Pull request merged**
