### PR TITLE
Added a new .py file which investigates Palettable

### PR DESCRIPTION
**Pull request by anshima1**
For further description of Palettable Package, follow the link, https://jiffyclub.github.io/palettable/

### CODE REVIEW

**Comment by ndanielsen** [comment]
hey @anshima1, thanks for checking out YB; we'll get back with you next week!

**Comment by bbengfort** [comment]
Hi @anshima1 thank you for looking into #115 - it's great that you're exploring how to contribute to open source libraries, and we're glad to have you contribute your third PR to us! 

My suggestion would be to transfer your python script to an ipython notebook in examples/anshima1/ -- this is where we put code that we're investigating or exploring. The questions to answer would be:

1. How do we adapt [yellowbrick.style.palettes. ColorPalette](https://github.com/DistrictDataLabs/yellowbrick/blob/develop/yellowbrick/style/palettes.py#L379) to use palettable input? 
2. Can we make a palettable color scheme available in a visualizer? 

Would you be willing to take on these questions?

**Comment by rebeccabilbro** [comment]
Hi there @anshima1 - are you still interested in working on this? Let us know if we can help!

**Comment by rebeccabilbro** [comment]
Hi again @anshima1 - I'm going to close this one out for now since the conversation has gone a bit stale, but feel free to open a new PR with the feedback that @bbengfort provided!

**Pull request closed without merging**
