### PR TITLE
feat: Add tests to Rank2D

### PR DESCRIPTION
**Pull request by rishacha**
This PR would add tests for testing
- [ ] Pearson,
- [ ] Covariance and
- [ ] Spearman rank-order correlation

in Rank2D.

Note : I've just opened this PR ( as mentioned in CONTRIBUTING.md ). Work in progress.

Ref: Github issue #628

### CODE REVIEW

**Comment by bbengfort** [comment]
Thanks @rishacha looking forward to seeing the tests!

**Comment by rebeccabilbro** [comment]
Hi @rishacha - just wanted to check in and see if this was still something you wanted to work on?

**Comment by rishacha** [comment]
Hi @rebeccabilbro, I am still figuring it out. I would need time till this weekend. If I can't finish it till then, you can take it. 

@bbengfort is there a discussion channel? IRC? I need some help.

**Comment by rebeccabilbro** [comment]
No problem @rishacha! Can you let me and @bbengfort know what you need help with?

**Comment by rebeccabilbro** [comment]
Ah ok, that particular dataset is likely from the UCI Machine Learning Repository ([here](https://archive.ics.uci.edu/ml/datasets/water+treatment+plant)). Downloading it and putting into a folder called `data` inside the `examples` repository should enable you to run that notebook. 

However, the notebooks in the examples folders are usually just experiments or artifacts of our development process, not part of the main library code. I don't think you'll need to run either this notebook or the examples.ipynb in order to write the tests, right? 

The tests you create for the rank2d will go in `/tests/test_features/test_rankd.py`, and you can use the [fixture dataset](https://github.com/DistrictDataLabs/yellowbrick/blob/develop/tests/test_features/test_rankd.py#L36-L46) that that test file creates when it runs, or any of the other classification datasets from the `tests.dataset` module. 

There are additional resources for writing Yellowbrick tests in our documentation [here](http://www.scikit-yb.org/en/latest/contributing.html#testing), which might be helpful to take a peek at. Let me know if you have any other questions!

**Comment by rebeccabilbro** [comment]
Hi there @rishacha - just wanted to check to see if this was something you still wanted to work on? We maintainers try to keep our PR dialogues from going stale, since they have an expiration date after a few weeks without updates. Let us know if there's anything you need from us to help move forward!

**Comment by rebeccabilbro** [comment]
Hi again @rishacha - going to go ahead and close this one out per the discussion above, but if you decide to come back to this, feel free to reopen and push more commits to your PR branch!

**Pull request closed without merging**
