### PR TITLE
Updates TSNE docs with plot directive and datasets module

### PR DESCRIPTION
**Pull request by rebeccabilbro**
This PR addresses portions of #687 and #683, which requested that the documentation be updated to use the new plot directive and to use the new datasets module in our docs.

I have made the following changes    
1. Updated `tsne.rst` to use the plot directive and hobbies corpus from the new datasets module. _Note that I elected to suppress the code blocks for the last two of the three images that are generated, since it is very repetitive._
2. Removed `tsne.py` since it is no longer need to generate the images.
3. Removed `tsne_no_labels.png`, `tsne_kmeans.png`, `tsne_all_docs.png` since these images will be generated via the plot directive when the docs are built.

### CODE REVIEW

**Comment by rebeccabilbro** [comment]
Thanks so much @Kautumn06!

**Comment by Sangarshanan** [comment]
Hey @rebeccabilbro I have written a small article on how yb can be used for rapid text visualization 
I would love to hear what you think. 

https://medium.com/@sangarshananveera/rapid-text-visualization-with-yellowbrick-51d3499c9333

**Comment by thisHermit** [comment]
Hi @rebeccabilbro ,
I was assigned to this issue by @lwgray . I found that the function load_corpus(path) is no longer needed due to the addition of the dataset package. Is it okay if I simply replace the contents of the function to make it compatible with the latest version? Or should I do this as well as the corrections ( fixing all occurences of load_corpus ) and then mark this function as depreciated? I hope I can help.

**Comment by lwgray** [comment]
@thisHermit i made a mistake it is Issue 855.  sorry

**Pull request merged**
