### PR TITLE
Datamodule

### PR DESCRIPTION
**Pull request by joshww43**
#219  Data Loading

Just to get a feel of the codebase

### CODE REVIEW

**Comment by ndanielsen** [comment]
@joshww43 let us know when this is ready for a review

**Comment by bbengfort** [comment]
@joshww43 note that I added a `download.py` to the yellowbrick library. It's used via:

```
$ python -m yellowbrick.download 
```

This is going to have to be part of your dataset implementation. I should also say that this issue is getting critical as I'm revamping the documentation -- I'll send you a note when I'm done so I can point you to the new docs.

**Comment by joshww43** [comment]
Thanks @bbengfort. Was abroad. Looking at download.py and clicked 'update this branch' based on the warning that the develop branch was head.

Any new docs?

**Comment by bbengfort** [comment]
@joshww43 let me know if you still plan on working on this or if you wouldn't mind me closing the PR to allow someone else to work on it.

**Pull request closed without merging**
