### PR TITLE
User Testing Notebook (Iris Dataset)  Connects with #124

### PR DESCRIPTION
**Pull request by ndanielsen**
Notebook with exercises generated using the (in)famous Iris dataset. No custom visualizers in this PR as that is the next step -- which will likely be a basic clustering visualizer for KNN using this dataset.

Also few bugs found as well as suggestions for improvements to the tutorial.

@pdamodaran go team!

### CODE REVIEW

**Comment by bbengfort** [comment]
@ndanielsen -- I couldn't view the notebook on GitHub for some reason; what version of Jupyter are you using? However, because you're adding a notebook, I approved the PR. 

Also, are you sure you want the example named nathan not ndanielsen? Was thinking of just using GitHub usernames, but that's ok with me if you want.

**Comment by bbengfort** [comment]
See #124

**Comment by ndanielsen** [comment]
hey Ben, good point. I'll change the folder name to my github name. Lastly, I'll take a look at notebook a little later. Also, probably best if I put a requirements file in my folder.

**Comment by bbengfort** [comment]
@ndanielsen ok cool, let me know when you're ready for me to review again!

**Comment by rebeccabilbro** [comment]
Bump @ndanielsen - we're ready to merge this in once you've updated the name in your examples directory to be your Github username

**Comment by ndanielsen** [comment]
@rebeccabilbro changed name of folder

**Pull request merged**
