### PR TITLE
Fix Travis Errors Related to switching method for making new directories in the Image Comparison Class

### LINKED ISSUE #916: Remove text from all Axes in image similarity tests
In a39df0d we added several text removal tools to streamline the image similarity tests, particularly for different operating systems. However, as discussed in #826 we are moving to multi-axes visualizers, particularly like the one in #884. The image similarity tests need to remove the ticks from all axes in the visualizer, not just the primary axes.

### PR DESCRIPTION
**Pull request by lwgray**
Fix Travis Errors Related to:

1.  Implement new way to create directories in Image Comparision Class
    We were getting Travis errors attributed to the fact that the current matplotlib.cbook.mkdir function was deprecated in MLP 3.0 To address this, the MPL function was changed to os.makedirs
2. Secondarily, we were getting an error stating that dataframes do not have a method "as_matrix". This is because "as_matrix()" has been deprecated.

This PR fixes #issue_number _(If you are fixing a bug)_ which reported a bug that caused a problem to occur when users...
Partially fixes #916 
_(or if you are introducing a new feature)_ which requested a feature to allow the user to...

I have made the following changes:

1. changed matplotlib.cbook.mkdir() to os.makedirs()
2. changed "df.as_matrix()" to "df.values" in contrib's scatter and boundaries visualizers
3.

### Sample Code and Plot

_If you are adding or modifying a visualizer, PLEASE include a sample plot here along with the code you used to generate it._

### TODOs and questions
What do I need to do to resolve the 2 image comparison failures?

1. Get rid of grid
2.  Increase Tolerance

Still to do:

- [ ] 
- [ ]
- [ ]

Questions for the @DistrictDataLabs/team-oz-maintainers:

- [ ]
- [ ]

### CHECKLIST

- [ ] _Is the commit message formatted correctly?_
- [ ] _Have you noted the new functionality/bugfix in the release notes of the next release?_

- [ ] _Included a sample plot to visually illustrate your changes?_
- [ ] _Do all of your functions and methods have docstrings?_
- [ ] _Have you added/updated unit tests where appropriate?_
- [ ] _Have you updated the baseline images if necessary?_
- [ ] _Have you run the unit tests using `pytest`?_
- [ ] _Is your code style correct (are you using PEP8, pyflakes)?_
- [ ] _Have you documented your new feature/functionality in the docs?_

- [ ] _Have you built the docs using `make html`?_

### CODE REVIEW

**Comment by rebeccabilbro** [comment]
@lwgray thanks for taking this one on! It looks like the `mkdirs` errors have been successfully resolved!

The remaining errors are `ImageComparisonFailures`, which may be due to other changes in matplotlib 3. Would you mind updating your local MPL to 3, re-running the tests locally, and pasting in below some of the before-and-after changes in the images that are resulting in failed image comparison tests (particularly those with high RSMEs)? E.g.:

`tests/actual_images/test_base/test_draw_visualizer_grid.png` vs
`tests/baseline_images/test_base/test_draw_visualizer_grid.png`
and `tests/actual_images/test_base/test_draw_visualizer_grid-failed-diff.png`


`tests/actual_images/test_contrib/test_missing/test_dispersion/test_missingvaluesdispersion_with_pandas_with_y_targets.png` vs `tests/baseline_images/test_contrib/test_missing/test_dispersion/test_missingvaluesdispersion_with_pandas_with_y_targets.png`
and `tests/actual_images/test_contrib/test_missing/test_dispersion/test_missingvaluesdispersion_with_pandas_with_y_targets-failed-diff.png`


`tests/actual_images/test_features/test_jointplot/test_columns_none_x_y_hist.png` vs
`tests/baseline_images/test_features/test_jointplot/test_columns_none_x_y_hist.png`
and `tests/actual_images/test_features/test_jointplot/test_columns_none_x_y_hist-failed-diff.png`

My guess is that something in MPL 3 has changed that affects how we're doing multi-axis plots, since those (and those with the manual legends) are the ones that appear to be failing, but taking a look at some examples should help!

**Comment by lwgray** [comment]
@rebeccabilbro will do! 😸

**Comment by lwgray** [comment]
@rebeccabilbro I already have MPL v3.1.2 and I am not getting any local ImageComparison Failures.  I do see failures due to
1. pandas [AttributeError: 'DataFrame' object has no attribute 'as_matrix']  in contrib visualizers (boundaries and scatter) tests
2. postag (LookupError: Error occurred because nltk postag data is not available)

**Comment by rebeccabilbro** [comment]
@lwgray the latest mpl seems to be 3.2, which is what will be installed on the Travis and Appveyor virtual machines when the CI tests run — can you try upgrading to that and rerunning tests? https://pypi.org/project/matplotlib/3.2.0/

**Comment by lwgray** [comment]
@rebeccabilbro I upgraded it to the latest release and received 40 failures.  Here are a few of the ImageComparisonFailures with diffs

tests/actual_images/test_draw/test_manual_legend.png 
tests/baseline_images/test_draw/test_manual_legend.png
image
image
image


Missing Values
tests/actual_images/test_contrib/test_missing/test_dispersion/test_missingvaluesdispersion_with_pandas_with_y_targets.png  tests/baseline_images/test_contrib/test_missing/test_dispersion/test_missingvaluesdispersion_with_pandas_with_y_targets.png
image
image
image

tests/actual_images/test_features/test_jointplot/test_columns_none_x_y.png
tests/baseline_images/test_features/test_jointplot/test_columns_none_x_y.png
image
image
image

**Comment by lwgray** [comment]
@rebeccabilbro I was able to get rid of all but 5 Image Comparison Errors.  I looked up MPL changelog and could not find anything that would lead to these ImageComparisontest failures.  Here are the tests that are failing.

test_base/test_draw_visualizer_grid
RMS 22.391

test_base/test_draw_with_rows
RMS 15.258

test_base/test_draw_with_cols
RMS 12.962

test_draw/test_manual_legend
RMS 8.159

test_meta/test_random_visualizer
RMS 17.359

The only solutions I could come up with were
1. Turn off grids
2. Increase tolerance

**Comment by rebeccabilbro** [comment]
Whew, @lwgray thank you so much for working on this &mdash; I apologize it's taken me so long to get back to you but this one is a real doozy! 

For a start, I went through your code changes, and the bugfixes for `cbook` and `as_matrix()` are perfect! 

Then I did my best to go through your other 200 changes to the images to ensure our baseline images play nicely with the [most recent release of matplotlib](https://matplotlib.org/3.2.1/users/whats_new.html), but I was having a little trouble understanding which ones were changed intentionally and which may have been unintentionally updated. For instance, I think their [kerning fix](https://matplotlib.org/3.2.1/users/whats_new.html#kerning-adjustments-now-use-correct-values) is a good one, and that we should update our baseline image that were impacted by that change, but it looked like that only impacted 7-8 of the images. As for the rest, it's hard to tell what exactly has changed in MPL that is affecting YB. 

From a maintenance perspective, my concern is that it is *possible* that some of the changes in MPL 3.2.1 are bugs, which would mean we might want to revert some of the image changes when the next MPL release comes out. For this reason, I've cut a new PR (#1053) that only changes the baseline images that were causing the test failures and leaves others the same, which I'm hoping will allow us to more easily retrace our steps should we need to.

I'm still waiting to see if that PR will survive the Appveyor/Miniconda gauntlet, but if it does, I would propose that we close this PR in favor of #1053 &mdash; any thoughts?

**Comment by lwgray** [comment]
@rebeccabilbro Thank you so much.  I actually thought the same and was worried that changes to the baseline images could be masking an underlying problem.  Thanks for reverting them back.

**Comment by rebeccabilbro** [comment]
Closing in favor of #1053 &mdash; thanks again @lwgray!

**Pull request closed without merging**
