### PR TITLE
[WIP] Make poof() return self.ax

### LINKED ISSUE #375: Poof() should return ax
Make sure that ll visualizers return the `self.ax` when calling poof(). This is so that users can always get access to the ax, for example when working inside a function in a notebook. In addition it will encourage the behavior pattern of tweaking the plot if desired after poof(). We will be adjusting our documentation to use this form to also encourage this behavior:

```
ax = viz.poof()
```

This why this behavior pattern is useful:
https://stackoverflow.com/questions/47450804/yellowbrick-increasing-font-size-on-yellowbrick-generated-charts

### PR DESCRIPTION
**Pull request by jtpio**
Initial work to make the `poof()` method return `self.ax`.

Fixes #375 

@DistrictDataLabs/team-oz-maintainers

### CODE REVIEW

**Comment by NealHumphrey** [comment]
@jtpio looks simple and straightforward. Were you able to search the codebase to see if any visualizers override the `poof()` method though? I can approve if you confirm there was at least a quick check for this. 

I checked on the failed appveyor integration and this was the reason, so should be safe to ignore: `Build execution time has reached the maximum allowed time for your plan (60 minutes).`. Python 3 test completed, Python 2 did not. 

This is very likely overkill for this issue, but for enforcing API uniformity for situations like this it would be ideal to include a test case that tests all subclasses of Visualizer, so if anyone overrides it'll catch it in the tests. @bbengfort or @ndanielsen I think we talked about this in the past but don't remember if we found a solution or just decided to keep watching out for things manually? If there's a working example of other unit tests that do API enforcement like this we could imitate, otherwise we can leave alone.

**Comment by jtpio** [comment]
Hi @NealHumphrey and @bbengfort,

Thanks for taking the time to review this change.
I think a proper pass on the over the codebase is still needed. Also this change alone doesn't seem to have any impact on https://github.com/DistrictDataLabs/yellowbrick/issues/380.

Will allocate time for a second look later this month.

**Comment by bbengfort** [comment]
@jtpio that would be great; thanks! let us know when you have a chance to look at it and if you have any questions!

**Comment by rebeccabilbro** [comment]
Hey there @jtpio - since the conversation has gone a bit stale here, I'm going to go ahead and close this one. Please feel free to open up a new PR as soon as you're ready to get back into this. We'd love to have you contribute!

**Pull request closed without merging**
