### PR TITLE
Allow marker style to be specified in Validation Curve

### PR DESCRIPTION
**Pull request by lwgray**
3. Summarize your PR (HINT: See CHECKLIST/TEMPLATE below!)
-->

This PR addresses StackOverflow question regarding how to change the marker of Validation Curve.
https://stackoverflow.com/questions/67267401/how-to-change-the-marker-in-yellowbrick-plots

I have made the following changes:

1. Added marker argument to both ValidationCurve and quickmethod

### Sample Code and Plot (Original [Top], New [Bottom])
```
import numpy as np

from yellowbrick.datasets import load_energy
from yellowbrick.model_selection import ValidationCurve

from sklearn.tree import DecisionTreeRegressor

# Load a regression dataset
X, y = load_energy()

viz = ValidationCurve(
    DecisionTreeRegressor(), param_name="max_depth",
    param_range=np.arange(1, 11), cv=10, scoring="r2",
    markers="-v"
)

# Fit and show the visualizer
viz.fit(X, y)
viz.show()
```
imageimage

### TODOs and questions

Still to do:

- [ ]
- [ ]
- [ ]

Questions for the @DistrictDataLabs/team-oz-maintainers:

- [ ]
- [ ]

### CHECKLIST

- [x] _Is the commit message formatted correctly?_
- [ ] _Have you noted the new functionality/bugfix in the release notes of the next release?_

- [x] _Included a sample plot to visually illustrate your changes?_
- [x] _Do all of your functions and methods have docstrings?_
- [ ] _Have you added/updated unit tests where appropriate?_
- [x] _Have you updated the baseline images if necessary?_
- [x] _Have you run the unit tests using `pytest`?_
- [x] _Is your code style correct (are you using PEP8, pyflakes)?_
- [ ] _Have you documented your new feature/functionality in the docs?_

- [ ] _Have you built the docs using `make html`?_

### CODE REVIEW

**Review by rebeccabilbro — APPROVED** [review]
Thanks so much @lwgray for making this update in response to the stackoverflow question about changing point markers. The code changes all look fine to me, and thank you for adding the new params to the docstrings of both the class and quick method. A suggestion: given that this PR was prompted by a user question, would you please also make an update to the validation curve documentation as it may preempt future user questions?

Two other housekeeping notes:
1. When I `pip install -r tests/requirements.txt`, I'm getting a warning that the version of scipy we have pinned does not exist:
```bash
ERROR: No matching distribution found for scipy==1.7.0
```
I propose we change it to a version of scipy that does exist. FYI - I built your branch locally with v1.8.0 and the tests ran without error.
2. Your PR is notifying us about a check annotation error in `docs/api/text/umap_vis.rst` regarding a plotting error; if that's something easy to fix (e.g. updating the umap version in `docs/requirements.txt`) perhaps we can quickly resolve it in this PR.

Thanks for being such a good steward of the YB project!

**Comment by lwgray** [comment]
@rebeccabilbro where are you seeing the annotation error?  During building the docs????

**Comment by rebeccabilbro** [comment]
> @rebeccabilbro where are you seeing the annotation error? During building the docs????

@lwgray look in your [PR diff in the “files changed” view, all the way at the bottom.](https://github.com/DistrictDataLabs/yellowbrick/pull/1258/files)

**Comment by lwgray** [comment]
@rebeccabilbro I am unsure how to resolve the umap annotation check.  Any suggestions?

**Comment by rebeccabilbro** [comment]
@lwgray ah ok - have you already tried updating the umap version in docs/requirements.txt as suggested above?

**Comment by lwgray** [comment]
docs/requirements doesn't have umap

**Comment by rebeccabilbro** [comment]
> docs/requirements doesn't have umap

That’s probably the problem :)

**Comment by lwgray** [comment]
@rebeccabilbro Adding umap to requirements doesn't resolve the issue....It is specific to this plot directive for umap quick-method as other umap Visualizer plot directives appear to run without issue

**Comment by rebeccabilbro** [comment]
FYI @lwgray this has been approved but left unmerged for over a month

**Comment by lwgray** [comment]
@rebeccabilbro  I didn't merge because i couldn't resolve the annotation error you brought up.  @bbengfort can you assist us?

**Comment by rebeccabilbro** [comment]
@lwgray Benjamin is on vacation. I'm going to merge this once the tests pass with @pdamodaran's updates. In the future, please merge your own PRs once you've received an approval.

**Comment by rebeccabilbro** [comment]
Unfortunately @lwgray it looks like you have a bit of new work to do to get all the image comparison checks to pass. Hopefully this won't take too much work on your part!

**Pull request merged**
