### PR TITLE
ROCAUC needs X/Y axis labels 

### PR DESCRIPTION
**Pull request by cjmorale**
@bbengfort  Added x and y axis to ROC curve. Updated example in docstring.

### CODE REVIEW

**Comment by ndanielsen** [comment]
@cjmorale this great work! thanks!

**Comment by cjmorale** [comment]
@bbengfort  since I do not have write access someone else will need to merge this branch right?

**Comment by bbengfort** [comment]
You should see a green button on the PR that says "squash and merge" -- once all the checks have passed, you're welcome to perform the merge. I can do it if you'd like, but we got some feedback that said contributors like hitting the merge button themselves.

**Comment by cjmorale** [comment]
@bbengfort I don't see that button so feel free to merge it in. 
image

**Comment by bbengfort** [comment]
Odd, that's too bad -- sorry about that!

**Pull request merged**
