### PR TITLE
Fixes #1160 Create random_state property to keep random_state in sync with PCA Transformer

### LINKED ISSUE #1160: pca_decomposition returns sometimes an exception
**Describe the bug**
Some time pca_decomposition finishes with an exception (AttributeError: 'PCA' object has no attribute 'random_state').
More precisely, the picture is well generated, but there is an exception just after (cf. traceback below).

**To Reproduce**

```python
from yellowbrick.datasets import load_credit
from yellowbrick.features import pca_decomposition

# Specify the features of interest and the target
X, y = load_credit()
classes = ['account in default', 'current with bills']

# Create, fit, and show the visualizer
pca_decomposition(
    X, y, scale=True, classes=classes
)
```

**Expected behavior**
The picture is generated without exception

**Traceback**

```
----------------------------------------------------------------------
AttributeError                       Traceback (most recent call last)
~/.local/lib/python3.8/site-packages/IPython/core/formatters.py in __call__(self, obj, include, exclude)
    968 
    969             if method is not None:
--> 970                 return method(include=include, exclude=exclude)
    971             return None
    972         else:

~/.local/lib/python3.8/site-packages/sklearn/base.py in _repr_mimebundle_(self, **kwargs)
    462     def _repr_mimebundle_(self, **kwargs):
    463         """Mime bundle used by jupyter kernels to display estimator"""
--> 464         output = {"text/plain": repr(self)}
    465         if get_config()["display"] == 'diagram':
    466             output["text/html"] = estimator_html_repr(self)

~/.local/lib/python3.8/site-packages/sklearn/base.py in __repr__(self, N_CHAR_MAX)
    258             n_max_elements_to_show=N_MAX_ELEMENTS_TO_SHOW)
    259 
--> 260         repr_ = pp.pformat(self)
    261 
    262         # Use bruteforce ellipsis when there are a lot of non-blank characters

~/anaconda3/lib/python3.8/pprint.py in pformat(self, object)
    151     def pformat(self, object):
    152         sio = _StringIO()
--> 153         self._format(object, sio, 0, 0, {}, 0)
    154         return sio.getvalue()
    155 

~/anaconda3/lib/python3.8/pprint.py in _format(self, object, stream, indent, allowance, context, level)
    168             self._readable = False
    169             return
--> 170         rep = self._repr(object, context, level)
    171         max_width = self._width - indent - allowance
    172         if len(rep) > max_width:

~/anaconda3/lib/python3.8/pprint.py in _repr(self, object, context, level)
    402 
    403     def _repr(self, object, context, level):
--> 404         repr, readable, recursive = self.format(object, context.copy(),
    405                                                 self._depth, level)
    406         if not readable:

~/.local/lib/python3.8/site-packages/sklearn/utils/_pprint.py in format(self, object, context, maxlevels, level)
    178 
    179     def format(self, object, context, maxlevels, level):
--> 180         return _safe_repr(object, context, maxlevels, level,
    181                           changed_only=self._changed_only)
    182 

~/.local/lib/python3.8/site-packages/sklearn/utils/_pprint.py in _safe_repr(object, context, maxlevels, level, changed_only)
    423         recursive = False
    424         if changed_only:
--> 425             params = _changed_params(object)
    426         else:
    427             params = object.get_params(deep=False)

~/.local/lib/python3.8/site-packages/sklearn/utils/_pprint.py in _changed_params(estimator)
     89     estimator with non-default values."""
     90 
---> 91     params = estimator.get_params(deep=False)
     92     init_func = getattr(estimator.__init__, 'deprecated_original',
     93                         estimator.__init__)

~/.local/lib/python3.8/site-packages/sklearn/base.py in get_params(self, deep)
    193         out = dict()
    194         for key in self._get_param_names():
--> 195             value = getattr(self, key)
    196             if deep and hasattr(value, 'get_params'):
    197                 deep_items = value.get_params().items()

AttributeError: 'PCA' object has no attribute 'random_state'

----------------------------------------------------------------------
AttributeError                       Traceback (most recent call last)
~/.local/lib/python3.8/site-packages/IPython/core/formatters.py in __call__(self, obj)
    700                 type_pprinters=self.type_printers,
    701                 deferred_pprinters=self.deferred_printers)
--> 702             printer.pretty(obj)
    703             printer.flush()
    704             return stream.getvalue()

~/.local/lib/python3.8/site-packages/IPython/lib/pretty.py in pretty(self, obj)
    392                         if cls is not object \
    393                                 and callable(cls.__dict__.get('__repr__')):
--> 394                             return _repr_pprint(obj, self, cycle)
    395 
    396             return _default_pprint(obj, self, cycle)

~/.local/lib/python3.8/site-packages/IPython/lib/pretty.py in _repr_pprint(obj, p, cycle)
    698     """A pprint that just redirects to the normal repr function."""
    699     # Find newlines and replace them with p.break_()
--> 700     output = repr(obj)
    701     lines = output.splitlines()
    702     with p.group():

~/.local/lib/python3.8/site-packages/sklearn/base.py in __repr__(self, N_CHAR_MAX)
    258             n_max_elements_to_show=N_MAX_ELEMENTS_TO_SHOW)
    259 
--> 260         repr_ = pp.pformat(self)
    261 
    262         # Use bruteforce ellipsis when there are a lot of non-blank characters

~/anaconda3/lib/python3.8/pprint.py in pformat(self, object)
    151     def pformat(self, object):
    152         sio = _StringIO()
--> 153         self._format(object, sio, 0, 0, {}, 0)
    154         return sio.getvalue()
    155 

~/anaconda3/lib/python3.8/pprint.py in _format(self, object, stream, indent, allowance, context, level)
    168             self._readable = False
    169             return
--> 170         rep = self._repr(object, context, level)
    171         max_width = self._width - indent - allowance
    172         if len(rep) > max_width:

~/anaconda3/lib/python3.8/pprint.py in _repr(self, object, context, level)
    402 
    403     def _repr(self, object, context, level):
--> 404         repr, readable, recursive = self.format(object, context.copy(),
    405                                                 self._depth, level)
    406         if not readable:

~/.local/lib/python3.8/site-packages/sklearn/utils/_pprint.py in format(self, object, context, maxlevels, level)
    178 
    179     def format(self, object, context, maxlevels, level):
--> 180         return _safe_repr(object, context, maxlevels, level,
    181                           changed_only=self._changed_only)
    182 

~/.local/lib/python3.8/site-packages/sklearn/utils/_pprint.py in _safe_repr(object, context, maxlevels, level, changed_only)
    423         recursive = False
    424         if changed_only:
--> 425             params = _changed_params(object)
    426         else:
    427             params = object.get_params(deep=False)

~/.local/lib/python3.8/site-packages/sklearn/utils/_pprint.py in _changed_params(estimator)
     89     estimator with non-default values."""
     90 
---> 91     params = estimator.get_params(deep=False)
     92     init_func = getattr(estimator.__init__, 'deprecated_original',
     93                         estimator.__init__)

~/.local/lib/python3.8/site-packages/sklearn/base.py in get_params(self, deep)
    193         out = dict()
    194         for key in self._get_param_names():
--> 195             value = getattr(self, key)
    196             if deep and hasattr(value, 'get_params'):
    197                 deep_items = value.get_params().items()

AttributeError: 'PCA' object has no attribute 'random_state'


```

**Desktop (please complete the following information):**
 - OS: linux
 - Python Version: 3.8
 - Yellowbrick Version: 1.3

**Additional information**
This bug is easy to correct, in  yellowbrick/features/pca.py:
actually : 
```
            colorbar=colorbar,
            **kwargs
        )

        # Data Parameters
        self.scale = scale
        self.proj_features = proj_features
```

correction :
```
            colorbar=colorbar,
            **kwargs
        )

        self.random_state=random_state
        # Data Parameters
        self.scale = scale
        self.proj_features = proj_features
```

### LINKED ISSUE #1167: ROC/AUC AttributeError: 'LogisticRegression' object has no attribute 'binary'
**Describe the bug**
Using logistic regression with the ROC/AUC functions throws `AttributeError: 'LogisticRegression' object has no attribute 'binary'`, however, the plot still shows up and it seems like most things work.

**To Reproduce**
This is the demo from the docs (https://www.scikit-yb.org/en/latest/api/classifier/rocauc.html):

```python
from yellowbrick.classifier.rocauc import roc_auc
from yellowbrick.datasets import load_credit
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

#Load the classification dataset
X, y = load_credit()

#Create the train and test data
X_train, X_test, y_train, y_test = train_test_split(X,y)

# Instantiate the visualizer with the classification model
model = LogisticRegression()
roc_auc(model, X_train, y_train, X_test=X_test, y_test=y_test, classes=['not_defaulted', 'defaulted'])
```

**Dataset**
From the demo.

**Expected behavior**
Should not throw an AttributeError.

**Traceback**

```python
AttributeError                            Traceback (most recent call last)
~\Anaconda3\envs\datasci\lib\site-packages\IPython\core\formatters.py in __call__(self, obj, include, exclude)
    968
    969             if method is not None:
--> 970                 return method(include=include, exclude=exclude)
    971             return None
    972         else:

~\Anaconda3\envs\datasci\lib\site-packages\sklearn\base.py in _repr_mimebundle_(self, **kwargs)
    462     def _repr_mimebundle_(self, **kwargs):
    463         """Mime bundle used by jupyter kernels to display estimator"""
--> 464         output = {"text/plain": repr(self)}
    465         if get_config()["display"] == 'diagram':
    466             output["text/html"] = estimator_html_repr(self)

~\Anaconda3\envs\datasci\lib\site-packages\sklearn\base.py in __repr__(self, N_CHAR_MAX)
    258             n_max_elements_to_show=N_MAX_ELEMENTS_TO_SHOW)
    259
--> 260         repr_ = pp.pformat(self)
    261
    262         # Use bruteforce ellipsis when there are a lot of non-blank characters

~\Anaconda3\envs\datasci\lib\pprint.py in pformat(self, object)
    151     def pformat(self, object):
    152         sio = _StringIO()
--> 153         self._format(object, sio, 0, 0, {}, 0)
    154         return sio.getvalue()
    155

~\Anaconda3\envs\datasci\lib\pprint.py in _format(self, object, stream, indent, allowance, context, level)
    168             self._readable = False
    169             return
--> 170         rep = self._repr(object, context, level)
    171         max_width = self._width - indent - allowance
    172         if len(rep) > max_width:

~\Anaconda3\envs\datasci\lib\pprint.py in _repr(self, object, context, level)
    402
    403     def _repr(self, object, context, level):
--> 404         repr, readable, recursive = self.format(object, context.copy(),
    405                                                 self._depth, level)
    406         if not readable:

~\Anaconda3\envs\datasci\lib\site-packages\sklearn\utils\_pprint.py in format(self, object, context, maxlevels, level)
    178
    179     def format(self, object, context, maxlevels, level):
--> 180         return _safe_repr(object, context, maxlevels, level,
    181                           changed_only=self._changed_only)
    182

~\Anaconda3\envs\datasci\lib\site-packages\sklearn\utils\_pprint.py in _safe_repr(object, context, maxlevels, level, changed_only)
    423         recursive = False
    424         if changed_only:
--> 425             params = _changed_params(object)
    426         else:
    427             params = object.get_params(deep=False)

~\Anaconda3\envs\datasci\lib\site-packages\sklearn\utils\_pprint.py in _changed_params(estimator)
     89     estimator with non-default values."""
     90
---> 91     params = estimator.get_params(deep=False)
     92     init_func = getattr(estimator.__init__, 'deprecated_original',
     93                         estimator.__init__)

~\Anaconda3\envs\datasci\lib\site-packages\yellowbrick\base.py in get_params(self, deep)
    340         the estimator params.
    341         """
--> 342         params = super(ModelVisualizer, self).get_params(deep=deep)
    343         for param in list(params.keys()):
    344             if param.startswith("estimator__"):

~\Anaconda3\envs\datasci\lib\site-packages\sklearn\base.py in get_params(self, deep)
    193         out = dict()
    194         for key in self._get_param_names():
--> 195             value = getattr(self, key)
    196             if deep and hasattr(value, 'get_params'):
    197                 deep_items = value.get_params().items()

~\Anaconda3\envs\datasci\lib\site-packages\yellowbrick\utils\wrapper.py in __getattr__(self, attr)
     40     def __getattr__(self, attr):
     41         # proxy to the wrapped object
---> 42         return getattr(self._wrapped, attr)

AttributeError: 'LogisticRegression' object has no attribute 'binary'
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~\Anaconda3\envs\datasci\lib\site-packages\IPython\core\formatters.py in __call__(self, obj)
    700                 type_pprinters=self.type_printers,
    701                 deferred_pprinters=self.deferred_printers)
--> 702             printer.pretty(obj)
    703             printer.flush()
    704             return stream.getvalue()

~\Anaconda3\envs\datasci\lib\site-packages\IPython\lib\pretty.py in pretty(self, obj)
    392                         if cls is not object \
    393                                 and callable(cls.__dict__.get('__repr__')):
--> 394                             return _repr_pprint(obj, self, cycle)
    395
    396             return _default_pprint(obj, self, cycle)

~\Anaconda3\envs\datasci\lib\site-packages\IPython\lib\pretty.py in _repr_pprint(obj, p, cycle)
    698     """A pprint that just redirects to the normal repr function."""
    699     # Find newlines and replace them with p.break_()
--> 700     output = repr(obj)
    701     lines = output.splitlines()
    702     with p.group():

~\Anaconda3\envs\datasci\lib\site-packages\sklearn\base.py in __repr__(self, N_CHAR_MAX)
    258             n_max_elements_to_show=N_MAX_ELEMENTS_TO_SHOW)
    259
--> 260         repr_ = pp.pformat(self)
    261
    262         # Use bruteforce ellipsis when there are a lot of non-blank characters

~\Anaconda3\envs\datasci\lib\pprint.py in pformat(self, object)
    151     def pformat(self, object):
    152         sio = _StringIO()
--> 153         self._format(object, sio, 0, 0, {}, 0)
    154         return sio.getvalue()
    155

~\Anaconda3\envs\datasci\lib\pprint.py in _format(self, object, stream, indent, allowance, context, level)
    168             self._readable = False
    169             return
--> 170         rep = self._repr(object, context, level)
    171         max_width = self._width - indent - allowance
    172         if len(rep) > max_width:

~\Anaconda3\envs\datasci\lib\pprint.py in _repr(self, object, context, level)
    402
    403     def _repr(self, object, context, level):
--> 404         repr, readable, recursive = self.format(object, context.copy(),
    405                                                 self._depth, level)
    406         if not readable:

~\Anaconda3\envs\datasci\lib\site-packages\sklearn\utils\_pprint.py in format(self, object, context, maxlevels, level)
    178
    179     def format(self, object, context, maxlevels, level):
--> 180         return _safe_repr(object, context, maxlevels, level,
    181                           changed_only=self._changed_only)
    182

~\Anaconda3\envs\datasci\lib\site-packages\sklearn\utils\_pprint.py in _safe_repr(object, context, maxlevels, level, changed_only)
    423         recursive = False
    424         if changed_only:
--> 425             params = _changed_params(object)
    426         else:
    427             params = object.get_params(deep=False)

~\Anaconda3\envs\datasci\lib\site-packages\sklearn\utils\_pprint.py in _changed_params(estimator)
     89     estimator with non-default values."""
     90
---> 91     params = estimator.get_params(deep=False)
     92     init_func = getattr(estimator.__init__, 'deprecated_original',
     93                         estimator.__init__)

~\Anaconda3\envs\datasci\lib\site-packages\yellowbrick\base.py in get_params(self, deep)
    340         the estimator params.
    341         """
--> 342         params = super(ModelVisualizer, self).get_params(deep=deep)
    343         for param in list(params.keys()):
    344             if param.startswith("estimator__"):

~\Anaconda3\envs\datasci\lib\site-packages\sklearn\base.py in get_params(self, deep)
    193         out = dict()
    194         for key in self._get_param_names():
--> 195             value = getattr(self, key)
    196             if deep and hasattr(value, 'get_params'):
    197                 deep_items = value.get_params().items()

~\Anaconda3\envs\datasci\lib\site-packages\yellowbrick\utils\wrapper.py in __getattr__(self, attr)
     40     def __getattr__(self, attr):
     41         # proxy to the wrapped object
---> 42         return getattr(self._wrapped, attr)

AttributeError: 'LogisticRegression' object has no attribute 'binary'
```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python Version 3.8 Anaconda
 - Yellowbrick Version current latest (1.3.post1)
 - sklearn version: 0.24.1

**Additional context**
I ran this in IPython, noticed a similar/the same bug in Jupyter.

### PR DESCRIPTION
**Pull request by lwgray**
This PR fixes #1160 which reported a bug that caused a problem to occur when users ran pca decomposition.  Some time pca_decomposition finishes with an exception (AttributeError: 'PCA' object has no attribute 'random_state').

I changed in accordance to @bbengfort conversation with submitter of issue #1160:

1. set self.random_state = random_state within the init
2. created property for random_state that sets the pca transformers random_state param

This PR also fixes #1167 which reported a bug that caused a problem to occur when users run rocauc.  An AttributeError would state that the model object has no attribute 'binary'

I changed:
1. set self.binary = binary

### CODE REVIEW

**Review by bbengfort — COMMENTED** [review]
@lwgray this looks great - thank you so much for fixing this bug! 

While you're here, would you mind fixing a similar bug? 

We need to add a `self.binary = binary` to https://github.com/DistrictDataLabs/yellowbrick/blob/develop/yellowbrick/classifier/rocauc.py#L211

**Comment by lwgray** [comment]
@bbengfort did you want me to fix that #1167 bug in this same PR?

**Comment by bbengfort** [comment]
@lwgray that would be great - it's just one additional line and they're related so I think it make sense to do it in the same PR.

**Comment by lwgray** [comment]
@bbengfort I made those changes...can I get a review?  Thanks!

**Review by bbengfort — APPROVED** [review]
@lwgray perfect, thank you so much for adding these changes. When we updated `get_params` and `set_params` for scikit-learn 0.24 compatibility in #1147 we created a requirement that any variables that are in the `__init__` signature must be stored as properties on the visualizer, because scikit-learn uses `inspect` to detect what are params and what are normal attributes. These are simple changes but they help a lot with compatibility for future versions of scikit-learn! 

It looks like all tests are passing, so I'm going to merge in the hopes that it fixes the develop branch tests!

**Pull request merged**
