### PR TITLE
[WIP] Added n_jobs argument for parallelization in K-Elbow Visualizer

### PR DESCRIPTION
**Pull request by saurabhdaalia**
This PR Fixes One of the Stretched Goal of #515 i.e adding `n_jobs` argument for using parallelized for the estimators.  
I have made the following changes    
1. added  `n_jobs` argument which can be passed as a parameter to the K-Elbow Visualiser. 
  
Still to do:
- [x] Adding `n_jobs` to the list of arguments in K-Elbow Visualiser API Documentation.

Questions for the @DistrictDataLabs/team-oz-maintainers:
1. When we consider parallelization, is there a need to parallelize the loop part where we fit estimators with different k values. 

2.
image
_Without passinng n_jobs argument passed_

image
_with n_jobs = -1_

Here I used a synthetic dataset of 1000 samples with 100 features. As per given docs https://scikit-learn.org/stable/glossary.html#term-n-jobs ,  n_jobs=-1 allows all CPUs to be used, but there is no overall improvement of fit time. 
Is it system dependent issue?

### CODE REVIEW

**Comment by lwgray** [comment]
@saurabhdaalia Thank you for this PR .  We are wading through our Backlog of issues and PRs but we will address this PR asap.

**Comment by saurabhdaalia** [comment]
@lwgray , Thank you. 

_Quick Question:  Can I start looking into other issues meanwhile or shall I wait for this PR to get through?_

**Comment by lwgray** [comment]
@saurabhdaalia  I really appreciate your enthusiasm and desire to contribute to YB - but perhaps we could focus on getting this shipped before opening a new PR ?

We're quite a small group and we do this in our spare time -- as you can probably tell we don't have a lot of surface area to deal with a large number of PRs!

**Comment by saurabhdaalia** [comment]
@lwgray , Sure, That sounds about right.

**Comment by rebeccabilbro** [comment]
@saurabhdaalia I appreciate your patience on this! Apologies for the delay but as you've probably noticed, this PR is currently blocked by #813, which makes a fair amount of changes to the same file (`yellowbrick/cluster/elbow.py`). As soon as that PR is complete and merged into develop, we'll get those changes integrated with your branch and proceed with reviewing your contribution!

**Comment by saurabhdaalia** [comment]
@rebeccabilbro sure, Thank you

**Comment by rebeccabilbro** [comment]
Hey there @saurabhdaalia &mdash; good news! #813 has been merged in, so we can now proceed with yours! Here's what to do next:
1. pull from the `develop` branch of yellowbrick into your feature branch
2. resolve any conflicts in the `yellowbrick/cluster/elbow.py` file manually on your machine
3. push the edits back to this PR branch
4. ping me when you're ready for a review!

**Comment by saurabhdaalia** [comment]
@rebeccabilbro , I have removed the conflicts and updated the branch.

**Comment by saurabhdaalia** [comment]
@rebeccabilbro , could you take a look at it and provide feedback?  It's ready to be reviewed,

**Comment by rebeccabilbro** [comment]
Hello @saurabhdaalia and thanks for keeping your branch up-to-date! With all the activity we've been having here lately, and considering the fact that we are all unpaid volunteers doing this in our spare time, we sincerely appreciate it!

I took a preliminary look through your modifications and wanted to send you some feedback; first of all, kudos for taking on one of @bbengfort's stretch goals for #515! As you probably guessed, it's labeled a "stretch goal" because it's implementation is going to require a bit more research and experimentation than a regular follow-up task. 

In this case, the goal is to refactor how we are currently doing the [`fit` loop over the different selected values of `k` ](https://github.com/DistrictDataLabs/yellowbrick/blob/92821b70f3e4da946b633ca92c9db5300c022acb/yellowbrick/cluster/elbow.py#L295). The current approach is to loop over every value of `k` passed in by the user, fit a centroidal model each time using that value of `k`, append the fit time to our timer attribute, and append the score to the scores attribute. However, you can imagine that this could go much faster if each k was passed to a different core and fit in parallel! So, what we are hoping for with this task is not merely to pass the n-jobs kwarg down from the YB visualizer into the scikit-learn visualizer, but to [use `joblib`](https://github.com/scikit-learn/scikit-learn/blob/0.17.X/sklearn/externals/joblib/parallel.py#L228) (to parallelize the multiple runs of `self.estimator.fit` for each `k`), similarly to how parallelization is implemented for something like [k-means in scikit-learn](https://github.com/scikit-learn/scikit-learn/blob/a47559461412d3424d2a3d2e71564053a32ea7d8/sklearn/cluster/k_means_.py#L388).

I realize that this is may require significantly more time and effort than you might have initially meant to bite off, but if you're game to start by doing a bit more research about how parallelization works in joblib and how it can be implemented using joblib's tools for our `ElbowVisualizer`, we'd be happy to support you through as you work through the process! If not, no hard feelings!

**Comment by saurabhdaalia** [comment]
@rebeccabilbro , Thank you for the feedback. Much appreciated !! 

As you can see, I have also asked this very issue in my PR details. Even I was curious to optimize the performance even more by somehow parallelizing multiple runs of `self.estimator.fit` for each `k`  and I am glad that I was on the right path of using `joblib` as you mentioned. 

_I implemented something similar to what is implemented in [k-means in scikit-learn ]_(https://github.com/scikit-learn/scikit-learn/blob/a47559461412d3424d2a3d2e71564053a32ea7d8/sklearn/cluster/k_means_.py#L388)

**For the speed comparison given below, I have  used a synthetic dataset of `10000 samples` with `1000 features `**

1.)  Using KElbowVisualiser with n_jobs i.e no parallelization 
image

2) Using KElbowVisualiser with n_jobs as -1 
image

As we can see there is roughly an increase of 30% in execution time. 

Right now, I am trying to wrap my head around various [backends](https://joblib.readthedocs.io/en/latest/parallel.html#thread-based-parallelism-vs-process-based-parallelism) used in joblib and which can decrease the overall execution time, as well as should we pass the n_jobs parameter to our estimator as well or not. 

_Let me know If I should update the PR with updated code and proceed further on this issue.  Feedback is much appreciated._

**Comment by rebeccabilbro** [comment]
Hey there @saurabhdaalia &mdash; glad that we were on the same page! It sounds like this task will probably take a bit more research into the complexities of joblib to get it across the finish line. So, if you've already started digging into the `joblib` internals, feel free to keep pushing on this. 

However, I noticed that you volunteered to be a new core contributor over the summer &mdash; that's awesome! For this reason, I might suggest that we instead archive this PR for now so that you can work with our Coordinator, @lwgray to pick out an issue that's more closely related to our v1.0 milestone that all our core contributors are now pushing to get done as soon as we can. Does that sound ok?

**Comment by saurabhdaalia** [comment]
@rebeccabilbro , Sure. That sounds fine. 

Thank you

**Comment by rebeccabilbro** [comment]
> @rebeccabilbro , Sure. That sounds fine.

Ok great! I'll let @lwgray know that you're on deck for a v1.0 milestone issue!

**Pull request closed without merging**
