### PR TITLE
New example notebook comparing tsne and umap

### PR DESCRIPTION
**Pull request by Sangarshanan**
Hello 

This is my first pull request so I have kept it simple and added an example notebook with a function that could rapidly compare the two corpus visualizers T-sne and UMAP 

I have also tried something that extends the FrequencyVisualizer to plot a Wordcloud. Would that be something that might add value to this amazing package ? Would appreciate feedback 

Thank you

### CODE REVIEW

**Comment by lwgray** [comment]
@Sangarshanan  We just came back from a lengthy hiatus and we are still catching up on our PRs and Issues.  Thank you for this PR.  We promise to get back to you ASAP.

**Comment by Sangarshanan** [comment]
> @Sangarshanan this is pretty neat! I'm happy to merge this in; though I'm wondering if you might also be interested in writing a blog post that uses this notebook as a starting point? For instance, it might help to add some textual interpretation to help people understand what it is we should be seeing in each successive plot, and how the plots might inform our decision making process for text modeling — let me know if you're interested and we can ping @ojedatony1616! Might be a better way to showcase your work and get the word out about how people are using YB!
> 
> P.S. if you wouldn't mind using the new yellowbrick datasets module (docs [here](https://github.com/DistrictDataLabs/yellowbrick#yellowbrick-datasets), example [here](https://www.scikit-yb.org/en/develop/api/text/dispersion.html)), that would be a great way to showcase how it works with text corpora.

**Comment by Sangarshanan** [comment]
@rebeccabilbro That sounds amazing. I would love to write a blog post and elaborate more on text modeling with YB. 
I checked out the dataset module...seems to make life simpler...Will definitely use it:)

**Comment by Sangarshanan** [comment]
Hey @rebeccabilbro I have written a small article on how yb can be used for rapid text visualization
I would love to hear what you think.

https://medium.com/@sangarshananveera/rapid-text-visualization-with-yellowbrick-51d3499c9333

**Comment by rebeccabilbro** [comment]
Wow @Sangarshanan this is so cool! Great work &mdash; I particularly like the illustration of how much stopwords removal improves the clustering of the different document categories! I think we should send this to @ojedatony1616 to see if he'd be interested in publishing a version on the District Data Labs blog!

**Comment by Sangarshanan** [comment]
Thank you @rebeccabilbro that's amazing.....glad you liked it :)

**Pull request merged**
