### PR TITLE
Feature importance Visualizer Improvement - Colors of Coef

### PR DESCRIPTION
**Pull request by lwgray**
This PR aims to resolve a singular problem of issue #322 
The problem I have chosen to resolve deals with the coloring of  the bars of the graph.
This problem consists of 2 aims:
#### Aim 1:
Problem: Apply different colors to the positive and negative coefficients.
Solution:   A slight alteration of the code provided by @bbengfort 

#### Aim 2:
Problem:  Allow user to specify which colors to use for positive and negative coefficients
Solution:  Used Yellowbrick.style function "resolve color"

### Example
importance

### CODE REVIEW

**Comment by bbengfort** [comment]
Also, it does look like this change broke the tests for feature importance; which may not be a bad thing - we just have to see what changed in the image and create a new baseline image if the change is reasonable.

**Comment by lwgray** [comment]
@bbengfort It's funny that you asked these questions b/c I have thought about most of these items.  In fact I had originally code exceptions but decided to leave them out b/c I thought the resolve_colors function could handle most of theses.  However, I will address each of these in a subsequent commit.

**Comment by bbengfort** [comment]
Hehe, you don't necessarily have to handle it with exceptions - documentation and test cases is fine also!

**Comment by ndanielsen** [comment]
just quick note that this is looking great so far and a fantastic contribution!

**Comment by bbengfort** [comment]
@lwgray please do a pull before you continue to work on this; I updated your branch pending the release of 0.6

**Pull request closed without merging**
